<?php

namespace Caiocesar173\Utils\Database\Seeders\GeoInfo\Area;

use Caiocesar173\Utils\Entities\Country;
use Caiocesar173\Utils\Entities\NetworkArea;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class NetworkAreaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::disableQueryLog();

        $networkAreas = [
            [
                "area_km2" => "647500",
                "country" => "Afghanistan",
                "e164" => "93",
                "hosts" => "223",
                "iso2" => "AF",
                "iso3" => "AFG",
                "iso_numeric" => "004",
                "level_domain" => "af",
                "users" => "1000000"
            ],
            [
                "area_km2" => "28748",
                "country" => "Albania",
                "e164" => "355",
                "hosts" => "15528",
                "iso2" => "AL",
                "iso3" => "ALB",
                "iso_numeric" => "008",
                "level_domain" => "al",
                "users" => "1300000"
            ],
            [
                "area_km2" => "2381740",
                "country" => "Algeria",
                "e164" => "213",
                "hosts" => "676",
                "iso2" => "DZ",
                "iso3" => "DZA",
                "iso_numeric" => "012",
                "level_domain" => "dz",
                "users" => "4700000"
            ],
            [
                "area_km2" => "199",
                "country" => "American Samoa",
                "e164" => "1",
                "hosts" => "2387",
                "iso2" => "AS",
                "iso3" => "ASM",
                "iso_numeric" => "016",
                "level_domain" => "as",
                "users" => ""
            ],
            [
                "area_km2" => "468",
                "country" => "Andorra",
                "e164" => "376",
                "hosts" => "28383",
                "iso2" => "AD",
                "iso3" => "AND",
                "iso_numeric" => "020",
                "level_domain" => "ad",
                "users" => "67100"
            ],
            [
                "area_km2" => "1246700",
                "country" => "Angola",
                "e164" => "244",
                "hosts" => "20703",
                "iso2" => "AO",
                "iso3" => "AGO",
                "iso_numeric" => "024",
                "level_domain" => "ao",
                "users" => "606700"
            ],
            [
                "area_km2" => "102",
                "country" => "Anguilla",
                "e164" => "1",
                "hosts" => "269",
                "iso2" => "AI",
                "iso3" => "AIA",
                "iso_numeric" => "660",
                "level_domain" => "ai",
                "users" => "3700"
            ],
            [
                "area_km2" => "14000000",
                "country" => "Antarctica",
                "e164" => "672",
                "hosts" => "7764",
                "iso2" => "AQ",
                "iso3" => "ATA",
                "iso_numeric" => "010",
                "level_domain" => "aq",
                "users" => ""
            ],
            [
                "area_km2" => "443",
                "country" => "Antigua and Barbuda",
                "e164" => "1",
                "hosts" => "11532",
                "iso2" => "AG",
                "iso3" => "ATG",
                "iso_numeric" => "028",
                "level_domain" => "ag",
                "users" => "65000"
            ],
            [
                "area_km2" => "2766890",
                "country" => "Argentina",
                "e164" => "54",
                "hosts" => "11232000",
                "iso2" => "AR",
                "iso3" => "ARG",
                "iso_numeric" => "032",
                "level_domain" => "ar",
                "users" => "13694000"
            ],
            [
                "area_km2" => "29800",
                "country" => "Armenia",
                "e164" => "374",
                "hosts" => "194142",
                "iso2" => "AM",
                "iso3" => "ARM",
                "iso_numeric" => "051",
                "level_domain" => "am",
                "users" => "208200"
            ],
            [
                "area_km2" => "193",
                "country" => "Aruba",
                "e164" => "297",
                "hosts" => "40560",
                "iso2" => "AW",
                "iso3" => "ABW",
                "iso_numeric" => "533",
                "level_domain" => "aw",
                "users" => "24000"
            ],
            [
                "area_km2" => "7686850",
                "country" => "Australia",
                "e164" => "61",
                "hosts" => "17081000",
                "iso2" => "AU",
                "iso3" => "AUS",
                "iso_numeric" => "036",
                "level_domain" => "au",
                "users" => "15810000"
            ],
            [
                "area_km2" => "83858",
                "country" => "Austria",
                "e164" => "43",
                "hosts" => "3512000",
                "iso2" => "AT",
                "iso3" => "AUT",
                "iso_numeric" => "040",
                "level_domain" => "at",
                "users" => "6143000"
            ],
            [
                "area_km2" => "86600",
                "country" => "Azerbaijan",
                "e164" => "994",
                "hosts" => "46856",
                "iso2" => "AZ",
                "iso3" => "AZE",
                "iso_numeric" => "031",
                "level_domain" => "az",
                "users" => "2420000"
            ],
            [
                "area_km2" => "13940",
                "country" => "Bahamas",
                "e164" => "1",
                "hosts" => "20661",
                "iso2" => "BS",
                "iso3" => "BHS",
                "iso_numeric" => "044",
                "level_domain" => "bs",
                "users" => "115800"
            ],
            [
                "area_km2" => "665",
                "country" => "Bahrain",
                "e164" => "973",
                "hosts" => "47727",
                "iso2" => "BH",
                "iso3" => "BHR",
                "iso_numeric" => "048",
                "level_domain" => "bh",
                "users" => "419500"
            ],
            [
                "area_km2" => "144000",
                "country" => "Bangladesh",
                "e164" => "880",
                "hosts" => "71164",
                "iso2" => "BD",
                "iso3" => "BGD",
                "iso_numeric" => "050",
                "level_domain" => "bd",
                "users" => "617300"
            ],
            [
                "area_km2" => "431",
                "country" => "Barbados",
                "e164" => "1",
                "hosts" => "1524",
                "iso2" => "BB",
                "iso3" => "BRB",
                "iso_numeric" => "052",
                "level_domain" => "bb",
                "users" => "188000"
            ],
            [
                "area_km2" => "207600",
                "country" => "Belarus",
                "e164" => "375",
                "hosts" => "295217",
                "iso2" => "BY",
                "iso3" => "BLR",
                "iso_numeric" => "112",
                "level_domain" => "by",
                "users" => "2643000"
            ],
            [
                "area_km2" => "30510",
                "country" => "Belgium",
                "e164" => "32",
                "hosts" => "5192000",
                "iso2" => "BE",
                "iso3" => "BEL",
                "iso_numeric" => "056",
                "level_domain" => "be",
                "users" => "8113000"
            ],
            [
                "area_km2" => "22966",
                "country" => "Belize",
                "e164" => "501",
                "hosts" => "3392",
                "iso2" => "BZ",
                "iso3" => "BLZ",
                "iso_numeric" => "084",
                "level_domain" => "bz",
                "users" => "36000"
            ],
            [
                "area_km2" => "112620",
                "country" => "Benin",
                "e164" => "229",
                "hosts" => "491",
                "iso2" => "BJ",
                "iso3" => "BEN",
                "iso_numeric" => "204",
                "level_domain" => "bj",
                "users" => "200100"
            ],
            [
                "area_km2" => "53",
                "country" => "Bermuda",
                "e164" => "1",
                "hosts" => "20040",
                "iso2" => "BM",
                "iso3" => "BMU",
                "iso_numeric" => "060",
                "level_domain" => "bm",
                "users" => "54000"
            ],
            [
                "area_km2" => "47000",
                "country" => "Bhutan",
                "e164" => "975",
                "hosts" => "14590",
                "iso2" => "BT",
                "iso3" => "BTN",
                "iso_numeric" => "064",
                "level_domain" => "bt",
                "users" => "50000"
            ],
            [
                "area_km2" => "1098580",
                "country" => "Bolivia",
                "e164" => "591",
                "hosts" => "180988",
                "iso2" => "BO",
                "iso3" => "BOL",
                "iso_numeric" => "068",
                "level_domain" => "bo",
                "users" => "1103000"
            ],
            [
                "area_km2" => "51129",
                "country" => "Bosnia and Herzegovina",
                "e164" => "387",
                "hosts" => "155252",
                "iso2" => "BA",
                "iso3" => "BIH",
                "iso_numeric" => "070",
                "level_domain" => "ba",
                "users" => "1422000"
            ],
            [
                "area_km2" => "600370",
                "country" => "Botswana",
                "e164" => "267",
                "hosts" => "1806",
                "iso2" => "BW",
                "iso3" => "BWA",
                "iso_numeric" => "072",
                "level_domain" => "bw",
                "users" => "120000"
            ],
            [
                "area_km2" => "8511965",
                "country" => "Brazil",
                "e164" => "55",
                "hosts" => "26577000",
                "iso2" => "BR",
                "iso3" => "BRA",
                "iso_numeric" => "076",
                "level_domain" => "br",
                "users" => "75982000"
            ],
            [
                "area_km2" => "60",
                "country" => "British Indian Ocean Territory",
                "e164" => "246",
                "hosts" => "75006",
                "iso2" => "IO",
                "iso3" => "IOT",
                "iso_numeric" => "086",
                "level_domain" => "io",
                "users" => ""
            ],
            [
                "area_km2" => "153",
                "country" => "British Virgin Islands",
                "e164" => "1",
                "hosts" => "505",
                "iso2" => "VG",
                "iso3" => "VGB",
                "iso_numeric" => "092",
                "level_domain" => "vg",
                "users" => "4000"
            ],
            [
                "area_km2" => "5770",
                "country" => "Brunei",
                "e164" => "673",
                "hosts" => "49457",
                "iso2" => "BN",
                "iso3" => "BRN",
                "iso_numeric" => "096",
                "level_domain" => "bn",
                "users" => "314900"
            ],
            [
                "area_km2" => "110910",
                "country" => "Bulgaria",
                "e164" => "359",
                "hosts" => "976277",
                "iso2" => "BG",
                "iso3" => "BGR",
                "iso_numeric" => "100",
                "level_domain" => "bg",
                "users" => "3395000"
            ],
            [
                "area_km2" => "274200",
                "country" => "Burkina Faso",
                "e164" => "226",
                "hosts" => "1795",
                "iso2" => "BF",
                "iso3" => "BFA",
                "iso_numeric" => "854",
                "level_domain" => "bf",
                "users" => "178100"
            ],
            [
                "area_km2" => "27830",
                "country" => "Burundi",
                "e164" => "257",
                "hosts" => "229",
                "iso2" => "BI",
                "iso3" => "BDI",
                "iso_numeric" => "108",
                "level_domain" => "bi",
                "users" => "157800"
            ],
            [
                "area_km2" => "181040",
                "country" => "Cambodia",
                "e164" => "855",
                "hosts" => "13784",
                "iso2" => "KH",
                "iso3" => "KHM",
                "iso_numeric" => "116",
                "level_domain" => "kh",
                "users" => "78500"
            ],
            [
                "area_km2" => "475440",
                "country" => "Cameroon",
                "e164" => "237",
                "hosts" => "10207",
                "iso2" => "CM",
                "iso3" => "CMR",
                "iso_numeric" => "120",
                "level_domain" => "cm",
                "users" => "749600"
            ],
            [
                "area_km2" => "9984670",
                "country" => "Canada",
                "e164" => "1",
                "hosts" => "8743000",
                "iso2" => "CA",
                "iso3" => "CAN",
                "iso_numeric" => "124",
                "level_domain" => "ca",
                "users" => "26960000"
            ],
            [
                "area_km2" => "4033",
                "country" => "Cape Verde",
                "e164" => "238",
                "hosts" => "38",
                "iso2" => "CV",
                "iso3" => "CPV",
                "iso_numeric" => "132",
                "level_domain" => "cv",
                "users" => "150000"
            ],
            [
                "area_km2" => "262",
                "country" => "Cayman Islands",
                "e164" => "1",
                "hosts" => "23472",
                "iso2" => "KY",
                "iso3" => "CYM",
                "iso_numeric" => "136",
                "level_domain" => "ky",
                "users" => "23000"
            ],
            [
                "area_km2" => "622984",
                "country" => "Central African Republic",
                "e164" => "236",
                "hosts" => "20",
                "iso2" => "CF",
                "iso3" => "CAF",
                "iso_numeric" => "140",
                "level_domain" => "cf",
                "users" => "22600"
            ],
            [
                "area_km2" => "1284000",
                "country" => "Chad",
                "e164" => "235",
                "hosts" => "6",
                "iso2" => "TD",
                "iso3" => "TCD",
                "iso_numeric" => "148",
                "level_domain" => "td",
                "users" => "168100"
            ],
            [
                "area_km2" => "756950",
                "country" => "Chile",
                "e164" => "56",
                "hosts" => "2152000",
                "iso2" => "CL",
                "iso3" => "CHL",
                "iso_numeric" => "152",
                "level_domain" => "cl",
                "users" => "7009000"
            ],
            [
                "area_km2" => "9596960",
                "country" => "China",
                "e164" => "86",
                "hosts" => "20602000",
                "iso2" => "CN",
                "iso3" => "CHN",
                "iso_numeric" => "156",
                "level_domain" => "cn",
                "users" => "389000000"
            ],
            [
                "area_km2" => "135",
                "country" => "Christmas Island",
                "e164" => "61",
                "hosts" => "3028",
                "iso2" => "CX",
                "iso3" => "CXR",
                "iso_numeric" => "162",
                "level_domain" => "cx",
                "users" => "464"
            ],
            [
                "area_km2" => "14",
                "country" => "Cocos Islands",
                "e164" => "61",
                "hosts" => "",
                "iso2" => "CC",
                "iso3" => "CCK",
                "iso_numeric" => "166",
                "level_domain" => "cc",
                "users" => ""
            ],
            [
                "area_km2" => "1138910",
                "country" => "Colombia",
                "e164" => "57",
                "hosts" => "4410000",
                "iso2" => "CO",
                "iso3" => "COL",
                "iso_numeric" => "170",
                "level_domain" => "co",
                "users" => "22538000"
            ],
            [
                "area_km2" => "2170",
                "country" => "Comoros",
                "e164" => "269",
                "hosts" => "14",
                "iso2" => "KM",
                "iso3" => "COM",
                "iso_numeric" => "174",
                "level_domain" => "km",
                "users" => "24300"
            ],
            [
                "area_km2" => "240",
                "country" => "Cook Islands",
                "e164" => "682",
                "hosts" => "3562",
                "iso2" => "CK",
                "iso3" => "COK",
                "iso_numeric" => "184",
                "level_domain" => "ck",
                "users" => "6000"
            ],
            [
                "area_km2" => "51100",
                "country" => "Costa Rica",
                "e164" => "506",
                "hosts" => "147258",
                "iso2" => "CR",
                "iso3" => "CRI",
                "iso_numeric" => "188",
                "level_domain" => "cr",
                "users" => "1485000"
            ],
            [
                "area_km2" => "56542",
                "country" => "Croatia",
                "e164" => "385",
                "hosts" => "729420",
                "iso2" => "HR",
                "iso3" => "HRV",
                "iso_numeric" => "191",
                "level_domain" => "hr",
                "users" => "2234000"
            ],
            [
                "area_km2" => "110860",
                "country" => "Cuba",
                "e164" => "53",
                "hosts" => "3244",
                "iso2" => "CU",
                "iso3" => "CUB",
                "iso_numeric" => "192",
                "level_domain" => "cu",
                "users" => "1606000"
            ],
            [
                "area_km2" => "444",
                "country" => "Curacao",
                "e164" => "599",
                "hosts" => "",
                "iso2" => "CW",
                "iso3" => "CUW",
                "iso_numeric" => "531",
                "level_domain" => "cw",
                "users" => ""
            ],
            [
                "area_km2" => "9250",
                "country" => "Cyprus",
                "e164" => "357",
                "hosts" => "252013",
                "iso2" => "CY",
                "iso3" => "CYP",
                "iso_numeric" => "196",
                "level_domain" => "cy",
                "users" => "433900"
            ],
            [
                "area_km2" => "78866",
                "country" => "Czech Republic",
                "e164" => "420",
                "hosts" => "4148000",
                "iso2" => "CZ",
                "iso3" => "CZE",
                "iso_numeric" => "203",
                "level_domain" => "cz",
                "users" => "6681000"
            ],
            [
                "area_km2" => "2345410",
                "country" => "Democratic Republic of the Congo",
                "e164" => "243",
                "hosts" => "2515",
                "iso2" => "CD",
                "iso3" => "COD",
                "iso_numeric" => "180",
                "level_domain" => "cd",
                "users" => "290000"
            ],
            [
                "area_km2" => "43094",
                "country" => "Denmark",
                "e164" => "45",
                "hosts" => "4297000",
                "iso2" => "DK",
                "iso3" => "DNK",
                "iso_numeric" => "208",
                "level_domain" => "dk",
                "users" => "4750000"
            ],
            [
                "area_km2" => "23000",
                "country" => "Djibouti",
                "e164" => "253",
                "hosts" => "215",
                "iso2" => "DJ",
                "iso3" => "DJI",
                "iso_numeric" => "262",
                "level_domain" => "dj",
                "users" => "25900"
            ],
            [
                "area_km2" => "754",
                "country" => "Dominica",
                "e164" => "1",
                "hosts" => "723",
                "iso2" => "DM",
                "iso3" => "DMA",
                "iso_numeric" => "212",
                "level_domain" => "dm",
                "users" => "28000"
            ],
            [
                "area_km2" => "48730",
                "country" => "Dominican Republic",
                "e164" => "1",
                "hosts" => "404500",
                "iso2" => "DO",
                "iso3" => "DOM",
                "iso_numeric" => "214",
                "level_domain" => "do",
                "users" => "2701000"
            ],
            [
                "area_km2" => "15007",
                "country" => "East Timor",
                "e164" => "670",
                "hosts" => "252",
                "iso2" => "TL",
                "iso3" => "TLS",
                "iso_numeric" => "626",
                "level_domain" => "tl",
                "users" => "2100"
            ],
            [
                "area_km2" => "283560",
                "country" => "Ecuador",
                "e164" => "593",
                "hosts" => "170538",
                "iso2" => "EC",
                "iso3" => "ECU",
                "iso_numeric" => "218",
                "level_domain" => "ec",
                "users" => "3352000"
            ],
            [
                "area_km2" => "1001450",
                "country" => "Egypt",
                "e164" => "20",
                "hosts" => "200430",
                "iso2" => "EG",
                "iso3" => "EGY",
                "iso_numeric" => "818",
                "level_domain" => "eg",
                "users" => "20136000"
            ],
            [
                "area_km2" => "21040",
                "country" => "El Salvador",
                "e164" => "503",
                "hosts" => "24070",
                "iso2" => "SV",
                "iso3" => "SLV",
                "iso_numeric" => "222",
                "level_domain" => "sv",
                "users" => "746000"
            ],
            [
                "area_km2" => "28051",
                "country" => "Equatorial Guinea",
                "e164" => "240",
                "hosts" => "7",
                "iso2" => "GQ",
                "iso3" => "GNQ",
                "iso_numeric" => "226",
                "level_domain" => "gq",
                "users" => "14400"
            ],
            [
                "area_km2" => "121320",
                "country" => "Eritrea",
                "e164" => "291",
                "hosts" => "701",
                "iso2" => "ER",
                "iso3" => "ERI",
                "iso_numeric" => "232",
                "level_domain" => "er",
                "users" => "200000"
            ],
            [
                "area_km2" => "45226",
                "country" => "Estonia",
                "e164" => "372",
                "hosts" => "865494",
                "iso2" => "EE",
                "iso3" => "EST",
                "iso_numeric" => "233",
                "level_domain" => "ee",
                "users" => "971700"
            ],
            [
                "area_km2" => "1127127",
                "country" => "Ethiopia",
                "e164" => "251",
                "hosts" => "179",
                "iso2" => "ET",
                "iso3" => "ETH",
                "iso_numeric" => "231",
                "level_domain" => "et",
                "users" => "447300"
            ],
            [
                "area_km2" => "12173",
                "country" => "Falkland Islands",
                "e164" => "500",
                "hosts" => "110",
                "iso2" => "FK",
                "iso3" => "FLK",
                "iso_numeric" => "238",
                "level_domain" => "fk",
                "users" => "2900"
            ],
            [
                "area_km2" => "1399",
                "country" => "Faroe Islands",
                "e164" => "298",
                "hosts" => "7575",
                "iso2" => "FO",
                "iso3" => "FRO",
                "iso_numeric" => "234",
                "level_domain" => "fo",
                "users" => "37500"
            ],
            [
                "area_km2" => "18270",
                "country" => "Fiji",
                "e164" => "679",
                "hosts" => "21739",
                "iso2" => "FJ",
                "iso3" => "FJI",
                "iso_numeric" => "242",
                "level_domain" => "fj",
                "users" => "114200"
            ],
            [
                "area_km2" => "337030",
                "country" => "Finland",
                "e164" => "358",
                "hosts" => "4763000",
                "iso2" => "FI",
                "iso3" => "FIN",
                "iso_numeric" => "246",
                "level_domain" => "fi",
                "users" => "4393000"
            ],
            [
                "area_km2" => "547030",
                "country" => "France",
                "e164" => "33",
                "hosts" => "17266000",
                "iso2" => "FR",
                "iso3" => "FRA",
                "iso_numeric" => "250",
                "level_domain" => "fr",
                "users" => "45262000"
            ],
            [
                "area_km2" => "4167",
                "country" => "French Polynesia",
                "e164" => "689",
                "hosts" => "37949",
                "iso2" => "PF",
                "iso3" => "PYF",
                "iso_numeric" => "258",
                "level_domain" => "pf",
                "users" => "120000"
            ],
            [
                "area_km2" => "267667",
                "country" => "Gabon",
                "e164" => "241",
                "hosts" => "127",
                "iso2" => "GA",
                "iso3" => "GAB",
                "iso_numeric" => "266",
                "level_domain" => "ga",
                "users" => "98800"
            ],
            [
                "area_km2" => "11300",
                "country" => "Gambia",
                "e164" => "220",
                "hosts" => "656",
                "iso2" => "GM",
                "iso3" => "GMB",
                "iso_numeric" => "270",
                "level_domain" => "gm",
                "users" => "130100"
            ],
            [
                "area_km2" => "69700",
                "country" => "Georgia",
                "e164" => "995",
                "hosts" => "357864",
                "iso2" => "GE",
                "iso3" => "GEO",
                "iso_numeric" => "268",
                "level_domain" => "ge",
                "users" => "1300000"
            ],
            [
                "area_km2" => "357021",
                "country" => "Germany",
                "e164" => "49",
                "hosts" => "20043000",
                "iso2" => "DE",
                "iso3" => "DEU",
                "iso_numeric" => "276",
                "level_domain" => "de",
                "users" => "65125000"
            ],
            [
                "area_km2" => "239460",
                "country" => "Ghana",
                "e164" => "233",
                "hosts" => "59086",
                "iso2" => "GH",
                "iso3" => "GHA",
                "iso_numeric" => "288",
                "level_domain" => "gh",
                "users" => "1297000"
            ],
            [
                "area_km2" => "7",
                "country" => "Gibraltar",
                "e164" => "350",
                "hosts" => "3509",
                "iso2" => "GI",
                "iso3" => "GIB",
                "iso_numeric" => "292",
                "level_domain" => "gi",
                "users" => "20200"
            ],
            [
                "area_km2" => "131940",
                "country" => "Greece",
                "e164" => "30",
                "hosts" => "3201000",
                "iso2" => "GR",
                "iso3" => "GRC",
                "iso_numeric" => "300",
                "level_domain" => "gr",
                "users" => "4971000"
            ],
            [
                "area_km2" => "2166086",
                "country" => "Greenland",
                "e164" => "299",
                "hosts" => "15645",
                "iso2" => "GL",
                "iso3" => "GRL",
                "iso_numeric" => "304",
                "level_domain" => "gl",
                "users" => "36000"
            ],
            [
                "area_km2" => "344",
                "country" => "Grenada",
                "e164" => "1",
                "hosts" => "80",
                "iso2" => "GD",
                "iso3" => "GRD",
                "iso_numeric" => "308",
                "level_domain" => "gd",
                "users" => "25000"
            ],
            [
                "area_km2" => "549",
                "country" => "Guam",
                "e164" => "1",
                "hosts" => "23",
                "iso2" => "GU",
                "iso3" => "GUM",
                "iso_numeric" => "316",
                "level_domain" => "gu",
                "users" => "90000"
            ],
            [
                "area_km2" => "108890",
                "country" => "Guatemala",
                "e164" => "502",
                "hosts" => "357552",
                "iso2" => "GT",
                "iso3" => "GTM",
                "iso_numeric" => "320",
                "level_domain" => "gt",
                "users" => "2279000"
            ],
            [
                "area_km2" => "78",
                "country" => "Guernsey",
                "e164" => "44",
                "hosts" => "239",
                "iso2" => "GG",
                "iso3" => "GGY",
                "iso_numeric" => "831",
                "level_domain" => "gg",
                "users" => "48300"
            ],
            [
                "area_km2" => "245857",
                "country" => "Guinea",
                "e164" => "224",
                "hosts" => "15",
                "iso2" => "GN",
                "iso3" => "GIN",
                "iso_numeric" => "324",
                "level_domain" => "gn",
                "users" => "95000"
            ],
            [
                "area_km2" => "36120",
                "country" => "Guinea-Bissau",
                "e164" => "245",
                "hosts" => "90",
                "iso2" => "GW",
                "iso3" => "GNB",
                "iso_numeric" => "624",
                "level_domain" => "gw",
                "users" => "37100"
            ],
            [
                "area_km2" => "214970",
                "country" => "Guyana",
                "e164" => "592",
                "hosts" => "24936",
                "iso2" => "GY",
                "iso3" => "GUY",
                "iso_numeric" => "328",
                "level_domain" => "gy",
                "users" => "189600"
            ],
            [
                "area_km2" => "27750",
                "country" => "Haiti",
                "e164" => "509",
                "hosts" => "555",
                "iso2" => "HT",
                "iso3" => "HTI",
                "iso_numeric" => "332",
                "level_domain" => "ht",
                "users" => "1000000"
            ],
            [
                "area_km2" => "112090",
                "country" => "Honduras",
                "e164" => "504",
                "hosts" => "30955",
                "iso2" => "HN",
                "iso3" => "HND",
                "iso_numeric" => "340",
                "level_domain" => "hn",
                "users" => "731700"
            ],
            [
                "area_km2" => "1092",
                "country" => "Hong Kong",
                "e164" => "852",
                "hosts" => "870041",
                "iso2" => "HK",
                "iso3" => "HKG",
                "iso_numeric" => "344",
                "level_domain" => "hk",
                "users" => "4873000"
            ],
            [
                "area_km2" => "93030",
                "country" => "Hungary",
                "e164" => "36",
                "hosts" => "3145000",
                "iso2" => "HU",
                "iso3" => "HUN",
                "iso_numeric" => "348",
                "level_domain" => "hu",
                "users" => "6176000"
            ],
            [
                "area_km2" => "103000",
                "country" => "Iceland",
                "e164" => "354",
                "hosts" => "369969",
                "iso2" => "IS",
                "iso3" => "ISL",
                "iso_numeric" => "352",
                "level_domain" => "is",
                "users" => "301600"
            ],
            [
                "area_km2" => "3287590",
                "country" => "India",
                "e164" => "91",
                "hosts" => "6746000",
                "iso2" => "IN",
                "iso3" => "IND",
                "iso_numeric" => "356",
                "level_domain" => "in",
                "users" => "61338000"
            ],
            [
                "area_km2" => "1919440",
                "country" => "Indonesia",
                "e164" => "62",
                "hosts" => "1344000",
                "iso2" => "ID",
                "iso3" => "IDN",
                "iso_numeric" => "360",
                "level_domain" => "id",
                "users" => "20000000"
            ],
            [
                "area_km2" => "1648000",
                "country" => "Iran",
                "e164" => "98",
                "hosts" => "197804",
                "iso2" => "IR",
                "iso3" => "IRN",
                "iso_numeric" => "364",
                "level_domain" => "ir",
                "users" => "8214000"
            ],
            [
                "area_km2" => "437072",
                "country" => "Iraq",
                "e164" => "964",
                "hosts" => "26",
                "iso2" => "IQ",
                "iso3" => "IRQ",
                "iso_numeric" => "368",
                "level_domain" => "iq",
                "users" => "325900"
            ],
            [
                "area_km2" => "70280",
                "country" => "Ireland",
                "e164" => "353",
                "hosts" => "1387000",
                "iso2" => "IE",
                "iso3" => "IRL",
                "iso_numeric" => "372",
                "level_domain" => "ie",
                "users" => "3042000"
            ],
            [
                "area_km2" => "572",
                "country" => "Isle of Man",
                "e164" => "44",
                "hosts" => "895",
                "iso2" => "IM",
                "iso3" => "IMN",
                "iso_numeric" => "833",
                "level_domain" => "im",
                "users" => ""
            ],
            [
                "area_km2" => "20770",
                "country" => "Israel",
                "e164" => "972",
                "hosts" => "2483000",
                "iso2" => "IL",
                "iso3" => "ISR",
                "iso_numeric" => "376",
                "level_domain" => "il",
                "users" => "4525000"
            ],
            [
                "area_km2" => "301230",
                "country" => "Italy",
                "e164" => "39",
                "hosts" => "25662000",
                "iso2" => "IT",
                "iso3" => "ITA",
                "iso_numeric" => "380",
                "level_domain" => "it",
                "users" => "29235000"
            ],
            [
                "area_km2" => "322460",
                "country" => "Ivory Coast",
                "e164" => "225",
                "hosts" => "9115",
                "iso2" => "CI",
                "iso3" => "CIV",
                "iso_numeric" => "384",
                "level_domain" => "ci",
                "users" => "967300"
            ],
            [
                "area_km2" => "10991",
                "country" => "Jamaica",
                "e164" => "1",
                "hosts" => "3906",
                "iso2" => "JM",
                "iso3" => "JAM",
                "iso_numeric" => "388",
                "level_domain" => "jm",
                "users" => "1581000"
            ],
            [
                "area_km2" => "377835",
                "country" => "Japan",
                "e164" => "81",
                "hosts" => "64453000",
                "iso2" => "JP",
                "iso3" => "JPN",
                "iso_numeric" => "392",
                "level_domain" => "jp",
                "users" => "99182000"
            ],
            [
                "area_km2" => "116",
                "country" => "Jersey",
                "e164" => "44",
                "hosts" => "264",
                "iso2" => "JE",
                "iso3" => "JEY",
                "iso_numeric" => "832",
                "level_domain" => "je",
                "users" => "29500"
            ],
            [
                "area_km2" => "92300",
                "country" => "Jordan",
                "e164" => "962",
                "hosts" => "69473",
                "iso2" => "JO",
                "iso3" => "JOR",
                "iso_numeric" => "400",
                "level_domain" => "jo",
                "users" => "1642000"
            ],
            [
                "area_km2" => "2717300",
                "country" => "Kazakhstan",
                "e164" => "7",
                "hosts" => "67464",
                "iso2" => "KZ",
                "iso3" => "KAZ",
                "iso_numeric" => "398",
                "level_domain" => "kz",
                "users" => "5299000"
            ],
            [
                "area_km2" => "582650",
                "country" => "Kenya",
                "e164" => "254",
                "hosts" => "71018",
                "iso2" => "KE",
                "iso3" => "KEN",
                "iso_numeric" => "404",
                "level_domain" => "ke",
                "users" => "3996000"
            ],
            [
                "area_km2" => "811",
                "country" => "Kiribati",
                "e164" => "686",
                "hosts" => "327",
                "iso2" => "KI",
                "iso3" => "KIR",
                "iso_numeric" => "296",
                "level_domain" => "ki",
                "users" => "7800"
            ],
            [
                "area_km2" => "10887",
                "country" => "Kosovo",
                "e164" => "383",
                "hosts" => "",
                "iso2" => "XK",
                "iso3" => "XKX",
                "iso_numeric" => "0",
                "level_domain" => "",
                "users" => ""
            ],
            [
                "area_km2" => "17820",
                "country" => "Kuwait",
                "e164" => "965",
                "hosts" => "2771",
                "iso2" => "KW",
                "iso3" => "KWT",
                "iso_numeric" => "414",
                "level_domain" => "kw",
                "users" => "1100000"
            ],
            [
                "area_km2" => "198500",
                "country" => "Kyrgyzstan",
                "e164" => "996",
                "hosts" => "115573",
                "iso2" => "KG",
                "iso3" => "KGZ",
                "iso_numeric" => "417",
                "level_domain" => "kg",
                "users" => "2195000"
            ],
            [
                "area_km2" => "236800",
                "country" => "Laos",
                "e164" => "856",
                "hosts" => "1532",
                "iso2" => "LA",
                "iso3" => "LAO",
                "iso_numeric" => "418",
                "level_domain" => "la",
                "users" => "300000"
            ],
            [
                "area_km2" => "64589",
                "country" => "Latvia",
                "e164" => "371",
                "hosts" => "359604",
                "iso2" => "LV",
                "iso3" => "LVA",
                "iso_numeric" => "428",
                "level_domain" => "lv",
                "users" => "1504000"
            ],
            [
                "area_km2" => "10400",
                "country" => "Lebanon",
                "e164" => "961",
                "hosts" => "64926",
                "iso2" => "LB",
                "iso3" => "LBN",
                "iso_numeric" => "422",
                "level_domain" => "lb",
                "users" => "1000000"
            ],
            [
                "area_km2" => "30355",
                "country" => "Lesotho",
                "e164" => "266",
                "hosts" => "11030",
                "iso2" => "LS",
                "iso3" => "LSO",
                "iso_numeric" => "426",
                "level_domain" => "ls",
                "users" => "76800"
            ],
            [
                "area_km2" => "111370",
                "country" => "Liberia",
                "e164" => "231",
                "hosts" => "7",
                "iso2" => "LR",
                "iso3" => "LBR",
                "iso_numeric" => "430",
                "level_domain" => "lr",
                "users" => "20000"
            ],
            [
                "area_km2" => "1759540",
                "country" => "Libya",
                "e164" => "218",
                "hosts" => "17926",
                "iso2" => "LY",
                "iso3" => "LBY",
                "iso_numeric" => "434",
                "level_domain" => "ly",
                "users" => "353900"
            ],
            [
                "area_km2" => "160",
                "country" => "Liechtenstein",
                "e164" => "423",
                "hosts" => "14278",
                "iso2" => "LI",
                "iso3" => "LIE",
                "iso_numeric" => "438",
                "level_domain" => "li",
                "users" => "23000"
            ],
            [
                "area_km2" => "65200",
                "country" => "Lithuania",
                "e164" => "370",
                "hosts" => "1205000",
                "iso2" => "LT",
                "iso3" => "LTU",
                "iso_numeric" => "440",
                "level_domain" => "lt",
                "users" => "1964000"
            ],
            [
                "area_km2" => "2586",
                "country" => "Luxembourg",
                "e164" => "352",
                "hosts" => "250900",
                "iso2" => "LU",
                "iso3" => "LUX",
                "iso_numeric" => "442",
                "level_domain" => "lu",
                "users" => "424500"
            ],
            [
                "area_km2" => "254",
                "country" => "Macau",
                "e164" => "853",
                "hosts" => "327",
                "iso2" => "MO",
                "iso3" => "MAC",
                "iso_numeric" => "446",
                "level_domain" => "mo",
                "users" => "270200"
            ],
            [
                "area_km2" => "25333",
                "country" => "Macedonia",
                "e164" => "389",
                "hosts" => "62826",
                "iso2" => "MK",
                "iso3" => "MKD",
                "iso_numeric" => "807",
                "level_domain" => "mk",
                "users" => "1057000"
            ],
            [
                "area_km2" => "587040",
                "country" => "Madagascar",
                "e164" => "261",
                "hosts" => "38392",
                "iso2" => "MG",
                "iso3" => "MDG",
                "iso_numeric" => "450",
                "level_domain" => "mg",
                "users" => "319900"
            ],
            [
                "area_km2" => "118480",
                "country" => "Malawi",
                "e164" => "265",
                "hosts" => "1099",
                "iso2" => "MW",
                "iso3" => "MWI",
                "iso_numeric" => "454",
                "level_domain" => "mw",
                "users" => "716400"
            ],
            [
                "area_km2" => "329750",
                "country" => "Malaysia",
                "e164" => "60",
                "hosts" => "422470",
                "iso2" => "MY",
                "iso3" => "MYS",
                "iso_numeric" => "458",
                "level_domain" => "my",
                "users" => "15355000"
            ],
            [
                "area_km2" => "300",
                "country" => "Maldives",
                "e164" => "960",
                "hosts" => "3296",
                "iso2" => "MV",
                "iso3" => "MDV",
                "iso_numeric" => "462",
                "level_domain" => "mv",
                "users" => "86400"
            ],
            [
                "area_km2" => "1240000",
                "country" => "Mali",
                "e164" => "223",
                "hosts" => "437",
                "iso2" => "ML",
                "iso3" => "MLI",
                "iso_numeric" => "466",
                "level_domain" => "ml",
                "users" => "249800"
            ],
            [
                "area_km2" => "316",
                "country" => "Malta",
                "e164" => "356",
                "hosts" => "14754",
                "iso2" => "MT",
                "iso3" => "MLT",
                "iso_numeric" => "470",
                "level_domain" => "mt",
                "users" => "240600"
            ],
            [
                "area_km2" => "181",
                "country" => "Marshall Islands",
                "e164" => "692",
                "hosts" => "3",
                "iso2" => "MH",
                "iso3" => "MHL",
                "iso_numeric" => "584",
                "level_domain" => "mh",
                "users" => "2200"
            ],
            [
                "area_km2" => "1030700",
                "country" => "Mauritania",
                "e164" => "222",
                "hosts" => "22",
                "iso2" => "MR",
                "iso3" => "MRT",
                "iso_numeric" => "478",
                "level_domain" => "mr",
                "users" => "75000"
            ],
            [
                "area_km2" => "2040",
                "country" => "Mauritius",
                "e164" => "230",
                "hosts" => "51139",
                "iso2" => "MU",
                "iso3" => "MUS",
                "iso_numeric" => "480",
                "level_domain" => "mu",
                "users" => "290000"
            ],
            [
                "area_km2" => "374",
                "country" => "Mayotte",
                "e164" => "262",
                "hosts" => "",
                "iso2" => "YT",
                "iso3" => "MYT",
                "iso_numeric" => "175",
                "level_domain" => "yt",
                "users" => ""
            ],
            [
                "area_km2" => "1972550",
                "country" => "Mexico",
                "e164" => "52",
                "hosts" => "16233000",
                "iso2" => "MX",
                "iso3" => "MEX",
                "iso_numeric" => "484",
                "level_domain" => "mx",
                "users" => "31020000"
            ],
            [
                "area_km2" => "702",
                "country" => "Micronesia",
                "e164" => "691",
                "hosts" => "4668",
                "iso2" => "FM",
                "iso3" => "FSM",
                "iso_numeric" => "583",
                "level_domain" => "fm",
                "users" => "17000"
            ],
            [
                "area_km2" => "33843",
                "country" => "Moldova",
                "e164" => "373",
                "hosts" => "711564",
                "iso2" => "MD",
                "iso3" => "MDA",
                "iso_numeric" => "498",
                "level_domain" => "md",
                "users" => "1333000"
            ],
            [
                "area_km2" => "2",
                "country" => "Monaco",
                "e164" => "377",
                "hosts" => "26009",
                "iso2" => "MC",
                "iso3" => "MCO",
                "iso_numeric" => "492",
                "level_domain" => "mc",
                "users" => "23000"
            ],
            [
                "area_km2" => "1565000",
                "country" => "Mongolia",
                "e164" => "976",
                "hosts" => "20084",
                "iso2" => "MN",
                "iso3" => "MNG",
                "iso_numeric" => "496",
                "level_domain" => "mn",
                "users" => "330000"
            ],
            [
                "area_km2" => "14026",
                "country" => "Montenegro",
                "e164" => "382",
                "hosts" => "10088",
                "iso2" => "ME",
                "iso3" => "MNE",
                "iso_numeric" => "499",
                "level_domain" => "me",
                "users" => "280000"
            ],
            [
                "area_km2" => "102",
                "country" => "Montserrat",
                "e164" => "1",
                "hosts" => "2431",
                "iso2" => "MS",
                "iso3" => "MSR",
                "iso_numeric" => "500",
                "level_domain" => "ms",
                "users" => "1200"
            ],
            [
                "area_km2" => "446550",
                "country" => "Morocco",
                "e164" => "212",
                "hosts" => "277338",
                "iso2" => "MA",
                "iso3" => "MAR",
                "iso_numeric" => "504",
                "level_domain" => "ma",
                "users" => "13213000"
            ],
            [
                "area_km2" => "801590",
                "country" => "Mozambique",
                "e164" => "258",
                "hosts" => "89737",
                "iso2" => "MZ",
                "iso3" => "MOZ",
                "iso_numeric" => "508",
                "level_domain" => "mz",
                "users" => "613600"
            ],
            [
                "area_km2" => "678500",
                "country" => "Myanmar",
                "e164" => "95",
                "hosts" => "1055",
                "iso2" => "MM",
                "iso3" => "MMR",
                "iso_numeric" => "104",
                "level_domain" => "mm",
                "users" => "110000"
            ],
            [
                "area_km2" => "825418",
                "country" => "Namibia",
                "e164" => "264",
                "hosts" => "78280",
                "iso2" => "NA",
                "iso3" => "NAM",
                "iso_numeric" => "516",
                "level_domain" => "na",
                "users" => "127500"
            ],
            [
                "area_km2" => "21",
                "country" => "Nauru",
                "e164" => "674",
                "hosts" => "8162",
                "iso2" => "NR",
                "iso3" => "NRU",
                "iso_numeric" => "520",
                "level_domain" => "nr",
                "users" => ""
            ],
            [
                "area_km2" => "140800",
                "country" => "Nepal",
                "e164" => "977",
                "hosts" => "41256",
                "iso2" => "NP",
                "iso3" => "NPL",
                "iso_numeric" => "524",
                "level_domain" => "np",
                "users" => "577800"
            ],
            [
                "area_km2" => "41526",
                "country" => "Netherlands",
                "e164" => "31",
                "hosts" => "13699000",
                "iso2" => "NL",
                "iso3" => "NLD",
                "iso_numeric" => "528",
                "level_domain" => "nl",
                "users" => "14872000"
            ],
            [
                "area_km2" => "19060",
                "country" => "New Caledonia",
                "e164" => "687",
                "hosts" => "34231",
                "iso2" => "NC",
                "iso3" => "NCL",
                "iso_numeric" => "540",
                "level_domain" => "nc",
                "users" => "85000"
            ],
            [
                "area_km2" => "268680",
                "country" => "New Zealand",
                "e164" => "64",
                "hosts" => "3026000",
                "iso2" => "NZ",
                "iso3" => "NZL",
                "iso_numeric" => "554",
                "level_domain" => "nz",
                "users" => "3400000"
            ],
            [
                "area_km2" => "129494",
                "country" => "Nicaragua",
                "e164" => "505",
                "hosts" => "296068",
                "iso2" => "NI",
                "iso3" => "NIC",
                "iso_numeric" => "558",
                "level_domain" => "ni",
                "users" => "199800"
            ],
            [
                "area_km2" => "1267000",
                "country" => "Niger",
                "e164" => "227",
                "hosts" => "454",
                "iso2" => "NE",
                "iso3" => "NER",
                "iso_numeric" => "562",
                "level_domain" => "ne",
                "users" => "115900"
            ],
            [
                "area_km2" => "923768",
                "country" => "Nigeria",
                "e164" => "234",
                "hosts" => "1234",
                "iso2" => "NG",
                "iso3" => "NGA",
                "iso_numeric" => "566",
                "level_domain" => "ng",
                "users" => "43989000"
            ],
            [
                "area_km2" => "260",
                "country" => "Niue",
                "e164" => "683",
                "hosts" => "79508",
                "iso2" => "NU",
                "iso3" => "NIU",
                "iso_numeric" => "570",
                "level_domain" => "nu",
                "users" => "1100"
            ],
            [
                "area_km2" => "120540",
                "country" => "North Korea",
                "e164" => "850",
                "hosts" => "8",
                "iso2" => "KP",
                "iso3" => "PRK",
                "iso_numeric" => "408",
                "level_domain" => "kp",
                "users" => ""
            ],
            [
                "area_km2" => "477",
                "country" => "Northern Mariana Islands",
                "e164" => "1",
                "hosts" => "17",
                "iso2" => "MP",
                "iso3" => "MNP",
                "iso_numeric" => "580",
                "level_domain" => "mp",
                "users" => ""
            ],
            [
                "area_km2" => "324220",
                "country" => "Norway",
                "e164" => "47",
                "hosts" => "3588000",
                "iso2" => "NO",
                "iso3" => "NOR",
                "iso_numeric" => "578",
                "level_domain" => "no",
                "users" => "4431000"
            ],
            [
                "area_km2" => "212460",
                "country" => "Oman",
                "e164" => "968",
                "hosts" => "14531",
                "iso2" => "OM",
                "iso3" => "OMN",
                "iso_numeric" => "512",
                "level_domain" => "om",
                "users" => "1465000"
            ],
            [
                "area_km2" => "803940",
                "country" => "Pakistan",
                "e164" => "92",
                "hosts" => "365813",
                "iso2" => "PK",
                "iso3" => "PAK",
                "iso_numeric" => "586",
                "level_domain" => "pk",
                "users" => "20431000"
            ],
            [
                "area_km2" => "458",
                "country" => "Palau",
                "e164" => "680",
                "hosts" => "4",
                "iso2" => "PW",
                "iso3" => "PLW",
                "iso_numeric" => "585",
                "level_domain" => "pw",
                "users" => ""
            ],
            [
                "area_km2" => "5970",
                "country" => "Palestine",
                "e164" => "970",
                "hosts" => "",
                "iso2" => "PS",
                "iso3" => "PSE",
                "iso_numeric" => "275",
                "level_domain" => "ps",
                "users" => "1379000"
            ],
            [
                "area_km2" => "78200",
                "country" => "Panama",
                "e164" => "507",
                "hosts" => "11022",
                "iso2" => "PA",
                "iso3" => "PAN",
                "iso_numeric" => "591",
                "level_domain" => "pa",
                "users" => "959800"
            ],
            [
                "area_km2" => "462840",
                "country" => "Papua New Guinea",
                "e164" => "675",
                "hosts" => "5006",
                "iso2" => "PG",
                "iso3" => "PNG",
                "iso_numeric" => "598",
                "level_domain" => "pg",
                "users" => "125000"
            ],
            [
                "area_km2" => "406750",
                "country" => "Paraguay",
                "e164" => "595",
                "hosts" => "280658",
                "iso2" => "PY",
                "iso3" => "PRY",
                "iso_numeric" => "600",
                "level_domain" => "py",
                "users" => "1105000"
            ],
            [
                "area_km2" => "1285220",
                "country" => "Peru",
                "e164" => "51",
                "hosts" => "234102",
                "iso2" => "PE",
                "iso3" => "PER",
                "iso_numeric" => "604",
                "level_domain" => "pe",
                "users" => "9158000"
            ],
            [
                "area_km2" => "300000",
                "country" => "Philippines",
                "e164" => "63",
                "hosts" => "425812",
                "iso2" => "PH",
                "iso3" => "PHL",
                "iso_numeric" => "608",
                "level_domain" => "ph",
                "users" => "8278000"
            ],
            [
                "area_km2" => "47",
                "country" => "Pitcairn",
                "e164" => "64",
                "hosts" => "",
                "iso2" => "PN",
                "iso3" => "PCN",
                "iso_numeric" => "612",
                "level_domain" => "pn",
                "users" => ""
            ],
            [
                "area_km2" => "312685",
                "country" => "Poland",
                "e164" => "48",
                "hosts" => "13265000",
                "iso2" => "PL",
                "iso3" => "POL",
                "iso_numeric" => "616",
                "level_domain" => "pl",
                "users" => "22452000"
            ],
            [
                "area_km2" => "92391",
                "country" => "Portugal",
                "e164" => "351",
                "hosts" => "3748000",
                "iso2" => "PT",
                "iso3" => "PRT",
                "iso_numeric" => "620",
                "level_domain" => "pt",
                "users" => "5168000"
            ],
            [
                "area_km2" => "9104",
                "country" => "Puerto Rico",
                "e164" => "1",
                "hosts" => "469",
                "iso2" => "PR",
                "iso3" => "PRI",
                "iso_numeric" => "630",
                "level_domain" => "pr",
                "users" => "1000000"
            ],
            [
                "area_km2" => "11437",
                "country" => "Qatar",
                "e164" => "974",
                "hosts" => "897",
                "iso2" => "QA",
                "iso3" => "QAT",
                "iso_numeric" => "634",
                "level_domain" => "qa",
                "users" => "563800"
            ],
            [
                "area_km2" => "342000",
                "country" => "Republic of the Congo",
                "e164" => "242",
                "hosts" => "45",
                "iso2" => "CG",
                "iso3" => "COG",
                "iso_numeric" => "178",
                "level_domain" => "cg",
                "users" => "245200"
            ],
            [
                "area_km2" => "2517",
                "country" => "Reunion",
                "e164" => "262",
                "hosts" => "",
                "iso2" => "RE",
                "iso3" => "REU",
                "iso_numeric" => "638",
                "level_domain" => "re",
                "users" => ""
            ],
            [
                "area_km2" => "237500",
                "country" => "Romania",
                "e164" => "40",
                "hosts" => "2667000",
                "iso2" => "RO",
                "iso3" => "ROU",
                "iso_numeric" => "642",
                "level_domain" => "ro",
                "users" => "7787000"
            ],
            [
                "area_km2" => "17100000",
                "country" => "Russia",
                "e164" => "7",
                "hosts" => "14865000",
                "iso2" => "RU",
                "iso3" => "RUS",
                "iso_numeric" => "643",
                "level_domain" => "ru",
                "users" => "40853000"
            ],
            [
                "area_km2" => "26338",
                "country" => "Rwanda",
                "e164" => "250",
                "hosts" => "1447",
                "iso2" => "RW",
                "iso3" => "RWA",
                "iso_numeric" => "646",
                "level_domain" => "rw",
                "users" => "450000"
            ],
            [
                "area_km2" => "21",
                "country" => "Saint Barthelemy",
                "e164" => "590",
                "hosts" => "",
                "iso2" => "BL",
                "iso3" => "BLM",
                "iso_numeric" => "652",
                "level_domain" => "gp",
                "users" => ""
            ],
            [
                "area_km2" => "410",
                "country" => "Saint Helena",
                "e164" => "290",
                "hosts" => "",
                "iso2" => "SH",
                "iso3" => "SHN",
                "iso_numeric" => "654",
                "level_domain" => "sh",
                "users" => ""
            ],
            [
                "area_km2" => "261",
                "country" => "Saint Kitts and Nevis",
                "e164" => "1",
                "hosts" => "54",
                "iso2" => "KN",
                "iso3" => "KNA",
                "iso_numeric" => "659",
                "level_domain" => "kn",
                "users" => "17000"
            ],
            [
                "area_km2" => "616",
                "country" => "Saint Lucia",
                "e164" => "1",
                "hosts" => "100",
                "iso2" => "LC",
                "iso3" => "LCA",
                "iso_numeric" => "662",
                "level_domain" => "lc",
                "users" => "142900"
            ],
            [
                "area_km2" => "53",
                "country" => "Saint Martin",
                "e164" => "1",
                "hosts" => "",
                "iso2" => "MF",
                "iso3" => "MAF",
                "iso_numeric" => "663",
                "level_domain" => "gp",
                "users" => ""
            ],
            [
                "area_km2" => "242",
                "country" => "Saint Pierre and Miquelon",
                "e164" => "508",
                "hosts" => "15",
                "iso2" => "PM",
                "iso3" => "SPM",
                "iso_numeric" => "666",
                "level_domain" => "pm",
                "users" => ""
            ],
            [
                "area_km2" => "389",
                "country" => "Saint Vincent and the Grenadines",
                "e164" => "1",
                "hosts" => "305",
                "iso2" => "VC",
                "iso3" => "VCT",
                "iso_numeric" => "670",
                "level_domain" => "vc",
                "users" => "76000"
            ],
            [
                "area_km2" => "2944",
                "country" => "Samoa",
                "e164" => "685",
                "hosts" => "18013",
                "iso2" => "WS",
                "iso3" => "WSM",
                "iso_numeric" => "882",
                "level_domain" => "ws",
                "users" => "9000"
            ],
            [
                "area_km2" => "61",
                "country" => "San Marino",
                "e164" => "378",
                "hosts" => "11015",
                "iso2" => "SM",
                "iso3" => "SMR",
                "iso_numeric" => "674",
                "level_domain" => "sm",
                "users" => "17000"
            ],
            [
                "area_km2" => "1001",
                "country" => "Sao Tome and Principe",
                "e164" => "239",
                "hosts" => "1678",
                "iso2" => "ST",
                "iso3" => "STP",
                "iso_numeric" => "678",
                "level_domain" => "st",
                "users" => "26700"
            ],
            [
                "area_km2" => "1960582",
                "country" => "Saudi Arabia",
                "e164" => "966",
                "hosts" => "145941",
                "iso2" => "SA",
                "iso3" => "SAU",
                "iso_numeric" => "682",
                "level_domain" => "sa",
                "users" => "9774000"
            ],
            [
                "area_km2" => "196190",
                "country" => "Senegal",
                "e164" => "221",
                "hosts" => "237",
                "iso2" => "SN",
                "iso3" => "SEN",
                "iso_numeric" => "686",
                "level_domain" => "sn",
                "users" => "1818000"
            ],
            [
                "area_km2" => "88361",
                "country" => "Serbia",
                "e164" => "381",
                "hosts" => "1102000",
                "iso2" => "RS",
                "iso3" => "SRB",
                "iso_numeric" => "688",
                "level_domain" => "rs",
                "users" => "4107000"
            ],
            [
                "area_km2" => "455",
                "country" => "Seychelles",
                "e164" => "248",
                "hosts" => "247",
                "iso2" => "SC",
                "iso3" => "SYC",
                "iso_numeric" => "690",
                "level_domain" => "sc",
                "users" => "32000"
            ],
            [
                "area_km2" => "71740",
                "country" => "Sierra Leone",
                "e164" => "232",
                "hosts" => "282",
                "iso2" => "SL",
                "iso3" => "SLE",
                "iso_numeric" => "694",
                "level_domain" => "sl",
                "users" => "14900"
            ],
            [
                "area_km2" => "693",
                "country" => "Singapore",
                "e164" => "65",
                "hosts" => "1960000",
                "iso2" => "SG",
                "iso3" => "SGP",
                "iso_numeric" => "702",
                "level_domain" => "sg",
                "users" => "3235000"
            ],
            [
                "area_km2" => "34",
                "country" => "Sint Maarten",
                "e164" => "1",
                "hosts" => "",
                "iso2" => "SX",
                "iso3" => "SXM",
                "iso_numeric" => "534",
                "level_domain" => "sx",
                "users" => ""
            ],
            [
                "area_km2" => "48845",
                "country" => "Slovakia",
                "e164" => "421",
                "hosts" => "1384000",
                "iso2" => "SK",
                "iso3" => "SVK",
                "iso_numeric" => "703",
                "level_domain" => "sk",
                "users" => "4063000"
            ],
            [
                "area_km2" => "20273",
                "country" => "Slovenia",
                "e164" => "386",
                "hosts" => "415581",
                "iso2" => "SI",
                "iso3" => "SVN",
                "iso_numeric" => "705",
                "level_domain" => "si",
                "users" => "1298000"
            ],
            [
                "area_km2" => "28450",
                "country" => "Solomon Islands",
                "e164" => "677",
                "hosts" => "4370",
                "iso2" => "SB",
                "iso3" => "SLB",
                "iso_numeric" => "090",
                "level_domain" => "sb",
                "users" => "10000"
            ],
            [
                "area_km2" => "637657",
                "country" => "Somalia",
                "e164" => "252",
                "hosts" => "186",
                "iso2" => "SO",
                "iso3" => "SOM",
                "iso_numeric" => "706",
                "level_domain" => "so",
                "users" => "106000"
            ],
            [
                "area_km2" => "1219912",
                "country" => "South Africa",
                "e164" => "27",
                "hosts" => "4761000",
                "iso2" => "ZA",
                "iso3" => "ZAF",
                "iso_numeric" => "710",
                "level_domain" => "za",
                "users" => "4420000"
            ],
            [
                "area_km2" => "98480",
                "country" => "South Korea",
                "e164" => "82",
                "hosts" => "315697",
                "iso2" => "KR",
                "iso3" => "KOR",
                "iso_numeric" => "410",
                "level_domain" => "kr",
                "users" => "39400000"
            ],
            [
                "area_km2" => "644329",
                "country" => "South Sudan",
                "e164" => "211",
                "hosts" => "",
                "iso2" => "SS",
                "iso3" => "SSD",
                "iso_numeric" => "728",
                "level_domain" => "ss",
                "users" => ""
            ],
            [
                "area_km2" => "504782",
                "country" => "Spain",
                "e164" => "34",
                "hosts" => "4228000",
                "iso2" => "ES",
                "iso3" => "ESP",
                "iso_numeric" => "724",
                "level_domain" => "es",
                "users" => "28119000"
            ],
            [
                "area_km2" => "65610",
                "country" => "Sri Lanka",
                "e164" => "94",
                "hosts" => "9552",
                "iso2" => "LK",
                "iso3" => "LKA",
                "iso_numeric" => "144",
                "level_domain" => "lk",
                "users" => "1777000"
            ],
            [
                "area_km2" => "1861484",
                "country" => "Sudan",
                "e164" => "249",
                "hosts" => "99",
                "iso2" => "SD",
                "iso3" => "SDN",
                "iso_numeric" => "729",
                "level_domain" => "sd",
                "users" => "4200000"
            ],
            [
                "area_km2" => "163270",
                "country" => "Suriname",
                "e164" => "597",
                "hosts" => "188",
                "iso2" => "SR",
                "iso3" => "SUR",
                "iso_numeric" => "740",
                "level_domain" => "sr",
                "users" => "163000"
            ],
            [
                "area_km2" => "62049",
                "country" => "Svalbard and Jan Mayen",
                "e164" => "47",
                "hosts" => "",
                "iso2" => "SJ",
                "iso3" => "SJM",
                "iso_numeric" => "744",
                "level_domain" => "sj",
                "users" => ""
            ],
            [
                "area_km2" => "17363",
                "country" => "Swaziland",
                "e164" => "268",
                "hosts" => "2744",
                "iso2" => "SZ",
                "iso3" => "SWZ",
                "iso_numeric" => "748",
                "level_domain" => "sz",
                "users" => "90100"
            ],
            [
                "area_km2" => "449964",
                "country" => "Sweden",
                "e164" => "46",
                "hosts" => "5978000",
                "iso2" => "SE",
                "iso3" => "SWE",
                "iso_numeric" => "752",
                "level_domain" => "se",
                "users" => "8398000"
            ],
            [
                "area_km2" => "41290",
                "country" => "Switzerland",
                "e164" => "41",
                "hosts" => "5301000",
                "iso2" => "CH",
                "iso3" => "CHE",
                "iso_numeric" => "756",
                "level_domain" => "ch",
                "users" => "6152000"
            ],
            [
                "area_km2" => "185180",
                "country" => "Syria",
                "e164" => "963",
                "hosts" => "416",
                "iso2" => "SY",
                "iso3" => "SYR",
                "iso_numeric" => "760",
                "level_domain" => "sy",
                "users" => "4469000"
            ],
            [
                "area_km2" => "35980",
                "country" => "Taiwan",
                "e164" => "886",
                "hosts" => "6272000",
                "iso2" => "TW",
                "iso3" => "TWN",
                "iso_numeric" => "158",
                "level_domain" => "tw",
                "users" => "16147000"
            ],
            [
                "area_km2" => "143100",
                "country" => "Tajikistan",
                "e164" => "992",
                "hosts" => "6258",
                "iso2" => "TJ",
                "iso3" => "TJK",
                "iso_numeric" => "762",
                "level_domain" => "tj",
                "users" => "700000"
            ],
            [
                "area_km2" => "945087",
                "country" => "Tanzania",
                "e164" => "255",
                "hosts" => "26074",
                "iso2" => "TZ",
                "iso3" => "TZA",
                "iso_numeric" => "834",
                "level_domain" => "tz",
                "users" => "678000"
            ],
            [
                "area_km2" => "514000",
                "country" => "Thailand",
                "e164" => "66",
                "hosts" => "3399000",
                "iso2" => "TH",
                "iso3" => "THA",
                "iso_numeric" => "764",
                "level_domain" => "th",
                "users" => "17483000"
            ],
            [
                "area_km2" => "56785",
                "country" => "Togo",
                "e164" => "228",
                "hosts" => "1168",
                "iso2" => "TG",
                "iso3" => "TGO",
                "iso_numeric" => "768",
                "level_domain" => "tg",
                "users" => "356300"
            ],
            [
                "area_km2" => "10",
                "country" => "Tokelau",
                "e164" => "690",
                "hosts" => "2069",
                "iso2" => "TK",
                "iso3" => "TKL",
                "iso_numeric" => "772",
                "level_domain" => "tk",
                "users" => "800"
            ],
            [
                "area_km2" => "748",
                "country" => "Tonga",
                "e164" => "676",
                "hosts" => "5367",
                "iso2" => "TO",
                "iso3" => "TON",
                "iso_numeric" => "776",
                "level_domain" => "to",
                "users" => "8400"
            ],
            [
                "area_km2" => "5128",
                "country" => "Trinidad and Tobago",
                "e164" => "1",
                "hosts" => "241690",
                "iso2" => "TT",
                "iso3" => "TTO",
                "iso_numeric" => "780",
                "level_domain" => "tt",
                "users" => "593000"
            ],
            [
                "area_km2" => "163610",
                "country" => "Tunisia",
                "e164" => "216",
                "hosts" => "576",
                "iso2" => "TN",
                "iso3" => "TUN",
                "iso_numeric" => "788",
                "level_domain" => "tn",
                "users" => "3500000"
            ],
            [
                "area_km2" => "780580",
                "country" => "Turkey",
                "e164" => "90",
                "hosts" => "7093000",
                "iso2" => "TR",
                "iso3" => "TUR",
                "iso_numeric" => "792",
                "level_domain" => "tr",
                "users" => "27233000"
            ],
            [
                "area_km2" => "488100",
                "country" => "Turkmenistan",
                "e164" => "993",
                "hosts" => "714",
                "iso2" => "TM",
                "iso3" => "TKM",
                "iso_numeric" => "795",
                "level_domain" => "tm",
                "users" => "80400"
            ],
            [
                "area_km2" => "430",
                "country" => "Turks and Caicos Islands",
                "e164" => "1",
                "hosts" => "73217",
                "iso2" => "TC",
                "iso3" => "TCA",
                "iso_numeric" => "796",
                "level_domain" => "tc",
                "users" => ""
            ],
            [
                "area_km2" => "26",
                "country" => "Tuvalu",
                "e164" => "688",
                "hosts" => "145158",
                "iso2" => "TV",
                "iso3" => "TUV",
                "iso_numeric" => "798",
                "level_domain" => "tv",
                "users" => "4200"
            ],
            [
                "area_km2" => "352",
                "country" => "U.S. Virgin Islands",
                "e164" => "1",
                "hosts" => "4790",
                "iso2" => "VI",
                "iso3" => "VIR",
                "iso_numeric" => "850",
                "level_domain" => "vi",
                "users" => "30000"
            ],
            [
                "area_km2" => "236040",
                "country" => "Uganda",
                "e164" => "256",
                "hosts" => "32683",
                "iso2" => "UG",
                "iso3" => "UGA",
                "iso_numeric" => "800",
                "level_domain" => "ug",
                "users" => "3200000"
            ],
            [
                "area_km2" => "603700",
                "country" => "Ukraine",
                "e164" => "380",
                "hosts" => "2173000",
                "iso2" => "UA",
                "iso3" => "UKR",
                "iso_numeric" => "804",
                "level_domain" => "ua",
                "users" => "7770000"
            ],
            [
                "area_km2" => "82880",
                "country" => "United Arab Emirates",
                "e164" => "971",
                "hosts" => "337804",
                "iso2" => "AE",
                "iso3" => "ARE",
                "iso_numeric" => "784",
                "level_domain" => "ae",
                "users" => "3449000"
            ],
            [
                "area_km2" => "244820",
                "country" => "United Kingdom",
                "e164" => "44",
                "hosts" => "8107000",
                "iso2" => "GB",
                "iso3" => "GBR",
                "iso_numeric" => "826",
                "level_domain" => "uk",
                "users" => "51444000"
            ],
            [
                "area_km2" => "9629091",
                "country" => "United States",
                "e164" => "1",
                "hosts" => "505000000",
                "iso2" => "US",
                "iso3" => "USA",
                "iso_numeric" => "840",
                "level_domain" => "us",
                "users" => "245000000"
            ],
            [
                "area_km2" => "176220",
                "country" => "Uruguay",
                "e164" => "598",
                "hosts" => "1036000",
                "iso2" => "UY",
                "iso3" => "URY",
                "iso_numeric" => "858",
                "level_domain" => "uy",
                "users" => "1405000"
            ],
            [
                "area_km2" => "447400",
                "country" => "Uzbekistan",
                "e164" => "998",
                "hosts" => "56075",
                "iso2" => "UZ",
                "iso3" => "UZB",
                "iso_numeric" => "860",
                "level_domain" => "uz",
                "users" => "4689000"
            ],
            [
                "area_km2" => "12200",
                "country" => "Vanuatu",
                "e164" => "678",
                "hosts" => "5655",
                "iso2" => "VU",
                "iso3" => "VUT",
                "iso_numeric" => "548",
                "level_domain" => "vu",
                "users" => "17000"
            ],
            [
                "area_km2" => "0",
                "country" => "Vatican",
                "e164" => "39",
                "hosts" => "",
                "iso2" => "VA",
                "iso3" => "VAT",
                "iso_numeric" => "336",
                "level_domain" => "va",
                "users" => ""
            ],
            [
                "area_km2" => "912050",
                "country" => "Venezuela",
                "e164" => "58",
                "hosts" => "1016000",
                "iso2" => "VE",
                "iso3" => "VEN",
                "iso_numeric" => "862",
                "level_domain" => "ve",
                "users" => "8918000"
            ],
            [
                "area_km2" => "329560",
                "country" => "Vietnam",
                "e164" => "84",
                "hosts" => "189553",
                "iso2" => "VN",
                "iso3" => "VNM",
                "iso_numeric" => "704",
                "level_domain" => "vn",
                "users" => "23382000"
            ],
            [
                "area_km2" => "274",
                "country" => "Wallis and Futuna",
                "e164" => "681",
                "hosts" => "2760",
                "iso2" => "WF",
                "iso3" => "WLF",
                "iso_numeric" => "876",
                "level_domain" => "wf",
                "users" => "1300"
            ],
            [
                "area_km2" => "266000",
                "country" => "Western Sahara",
                "e164" => "212",
                "hosts" => "",
                "iso2" => "EH",
                "iso3" => "ESH",
                "iso_numeric" => "732",
                "level_domain" => "eh",
                "users" => ""
            ],
            [
                "area_km2" => "527970",
                "country" => "Yemen",
                "e164" => "967",
                "hosts" => "33206",
                "iso2" => "YE",
                "iso3" => "YEM",
                "iso_numeric" => "887",
                "level_domain" => "ye",
                "users" => "2349000"
            ],
            [
                "area_km2" => "752614",
                "country" => "Zambia",
                "e164" => "260",
                "hosts" => "16571",
                "iso2" => "ZM",
                "iso3" => "ZMB",
                "iso_numeric" => "894",
                "level_domain" => "zm",
                "users" => "816200"
            ],
            [
                "area_km2" => "390580",
                "country" => "Zimbabwe",
                "e164" => "263",
                "hosts" => "30615",
                "iso2" => "ZW",
                "iso3" => "ZWE",
                "iso_numeric" => "716",
                "level_domain" => "zw",
                "users" => "1423000"
            ]
        ];

        Schema::disableForeignKeyConstraints();
        DB::table('network_areas')->truncate();
        $counter = 0;
        foreach ($networkAreas as $network) {
            $countryName = $network["iso2"];
            $country = Country::where('code', $countryName)->first();

            if (is_null($country))
                throw new \Exception("unable to find country: $countryName", 1);

            $network['country'] = $country->id;

            $save = NetworkArea::create($network);
            if (is_string($save))
                throw new \Exception($save, 1);

            if ($this->command)
                $this->command->info("Inserted network from {$network['hosts']} [$counter].");
            else
                echo("Inserted network from {$network['hosts']} [$counter].\n");

            $counter += 1;
        }
        Schema::enableForeignKeyConstraints();
    }
}
