<?php

namespace Caiocesar173\Utils\Database\Seeds;

use Caiocesar173\Utils\Entities\Permission;
use Caiocesar173\Utils\Entities\PermissionItem;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Caiocesar173\Utils\Entities\PermissionMap;


class PermissionMaps extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::disableQueryLog();
        $permisson_map = []; #laksdjfasdfsdfg
            $permisson_map = []; #laksdjfasdfsdfg
                $permisson_map = []; #laksdjfasdfsdfg


        
        $permisson_map = [
            [   'Presidência'               ,'user'                     ],
            [   'Presidência'               ,'list_user'                ],
            [   'Presidência'               ,'list_single_user'         ],
            [   'Presidência'               ,'manager'                  ],
            [   'Presidência'               ,'associate_manager'        ],
            [   'Presidência'               ,'list_manager'             ],
            [   'Presidência'               ,'list_single_manager'      ],
            [   'Presidência'               ,'edit_single_user'         ],
            [   'Presidência'               ,'delete_user'              ],
            [   'Presidência'               ,'manager'                  ],
            [   'Presidência'               ,'passalt_single_user'      ],
            [   'Presidência'               ,'passalt_user'             ],
            [   'Presidência'               ,'edit_user'                ],
            [   'Presidência'               ,'client_create'            ],
            [   'Presidência'               ,'client_list'              ],
            [   'Presidência'               ,'client_list_single'       ],
            [   'Presidência'               ,'client_edit'              ],
            [   'Presidência'               ,'client_edit_single'       ],
            [   'Presidência'               ,'client_delete'            ],
            [   'Presidência'               ,'provider_create'          ],
            [   'Presidência'               ,'provider_list'            ],
            [   'Presidência'               ,'provider_list_single'     ],
            [   'Presidência'               ,'provider_edit'            ],
            [   'Presidência'               ,'provider_edit_single'     ],
            [   'Presidência'               ,'provider_delete'          ],
            [   'Presidência'               ,'prov_product_create'      ],
            [   'Presidência'               ,'prov_product_list'        ],
            [   'Presidência'               ,'prov_product_list_single' ],
            [   'Presidência'               ,'prov_product_edit'        ],
            [   'Presidência'               ,'prov_product_edit_single' ],
            [   'Presidência'               ,'prov_product_delete'      ],
            [   'Presidência'               ,'product_create'           ],
            [   'Presidência'               ,'product_list'             ],
            [   'Presidência'               ,'product_list_single'      ],
            [   'Presidência'               ,'product_edit'             ],
            [   'Presidência'               ,'product_edit_single'      ],
            [   'Presidência'               ,'product_delete'           ],
            [   'Presidência'               ,'prod_type_create'         ],
            [   'Presidência'               ,'prod_type_list'           ],
            [   'Presidência'               ,'prod_type_list_single'    ],
            [   'Presidência'               ,'prod_type_edit'           ],
            [   'Presidência'               ,'prod_type_edit_single'    ],
            [   'Presidência'               ,'prod_type_delete'         ],
            [   'Presidência'               ,'order_create'             ],
            [   'Presidência'               ,'order_aprove'             ],
            [   'Presidência'               ,'order_reprove'            ],
            [   'Presidência'               ,'order_backoffice'         ],
            [   'Presidência'               ,'order_list'               ],
            [   'Presidência'               ,'order'                    ],
            [   'Presidência'               ,'order_edit'               ],
            [   'Presidência'               ,'order_create'             ],
            [   'Presidência'               ,'order_delete'             ],
            [   'Presidência'               ,'order_batches_finish'     ],
            [   'Presidência'               ,'order_finish'             ],
            [   'Presidência'               ,'order_edit'               ],
            [   'Presidência'               ,'order_delete'             ],
            [   'Presidência'               ,'order_item'               ],
            [   'Presidência'               ,'order_item_create'        ],
            [   'Presidência'               ,'order_item_list'          ],
            [   'Presidência'               ,'order_item_edit'          ],
            [   'Presidência'               ,'order_item_delte'         ],
            [   'Presidência'               ,'order_batch'              ],
            [   'Presidência'               ,'order_batch_create'       ],
            [   'Presidência'               ,'order_batch_list'         ],
            [   'Presidência'               ,'order_batch_edit'         ],
            [   'Presidência'               ,'order_batch_delete'       ],
            [   'Presidência'               ,'order_batch_link'         ],
            [   'Presidência'               ,'order_batch_finish'       ],
            [   'Presidência'               ,'see_inventary'            ],
            [   'Presidência'               ,'see_dashboard'            ],
            [   'Presidência'               ,'see_orders'               ],
            [   'Presidência'               ,'active_lines'             ],
            [   'Presidência'               ,'send_sms'                 ],
            [   'Presidência'               ,'operational_manager'      ],
            [   'Presidência'               ,'see_stock'                ],
            [   'Presidência'               ,'see_batchs'               ],
            [   'Presidência'               ,'see_stock_itens'          ],
            [   'Presidência'               ,'see_customers'            ],
            [   'Presidência'               ,'see_invoices'             ],
            [   'Presidência'               ,'see_users'                ],
            [   "Cliente" 	                ,"user"                     ],
            [   "Presidência"               ,"user"                     ],
            [   "Desenvolvedor"             ,"user"                     ],
            [   "Logística"                 ,"user"                     ],
            [   "Faturamento"               ,"user"                     ],
            [   "Gerente de Contas"         ,"user"                     ],
            [   "Financeiro"                ,"user"                     ],
            [   "Cliente"                   ,"user"                     ],
            [   "Suporte"                   ,"user"                     ],
            [   "Presidência"               ,"user"                     ],
            [   "Desenvolvedor"             ,"user"                     ],
            [   "Gerente de Contas"         ,"user"                     ],
            [   "Financeiro"                ,"user"                     ],
            [   "Cliente"                   ,"user"                     ],
            [   "Suporte"                   ,"user"                     ],
            [   "Controle de Qualidade"     ,"user"                     ],
            [   "Gerente operacional"       ,"user"                     ],
            [   "Desenvolvedor Junior"      ,"user"                     ],
            [   "Desenvolvedor Senior"      ,"user"                     ],
            [   "DBA"                       ,"user"                     ],
            [   "DBA Junior"                ,"user"                     ],
            [   "DBA Senior"                ,"user"                     ],
            [   "Sistema"                   ,"user"                     ],
            [   "Presidência"               ,"list_user"                ],
            [   "Desenvolvedor"             ,"list_user"                ],
            [   "Gerente de Contas"         ,"list_user"                ],
            [   "Financeiro" ,"list_user" ],
            [   "Cliente" ,"list_user" ],
            [   "Suporte" ,"list_user" ],
            [   "Controle de Qualidade" ,"list_user" ],
            [   "Gerente operacional" ,"list_user" ],
            [   "Desenvolvedor Junior" ,"list_user" ],
            [   "Desenvolvedor Senior" ,"list_user" ],
            [   "DBA" ,"list_user" ],
            [   "DBA Junior" ,"list_user" ],
            [   "DBA Senior" ,"list_user" ],
            [   "Sistema" ,"list_user" ],
            [   "Presidência" ,"list_user" ],
            [   "Desenvolvedor" ,"list_user" ],
            [   "Gerente de Contas" ,"list_user" ],
            [   "Financeiro" ,"list_user" ],
            [   "Cliente" ,"list_user" ],
            [   "Suporte" ,"list_user" ],
            [   "Controle de Qualidade" ,"list_user" ],
            [   "Gerente operacional" ,"list_user" ],
            [   "Desenvolvedor Junior" ,"list_user" ],
            [   "Desenvolvedor Senior" ,"list_user" ],
            [   "DBA" ,"list_user" ],
            [   "DBA Junior" ,"list_user" ],
            [   "DBA Senior" ,"list_user" ],
            [   "Sistema" ,"list_user" ],
            [   "Presidência" ,"list_single_user" ],
            [   "Desenvolvedor" ,"list_single_user" ],
            [   "Gerente de Contas" ,"list_single_user" ],
            [   "Financeiro" ,"list_single_user" ],
            [   "Cliente" ,"list_single_user" ],
            [   "Suporte" ,"list_single_user" ],
            [   "Controle de Qualidade" ,"list_single_user" ],
            [   "Gerente operacional" ,"list_single_user" ],
            [   "Desenvolvedor Junior" ,"list_single_user" ],
            [   "Desenvolvedor Senior" ,"list_single_user" ],
            [   "DBA" ,"list_single_user" ],
            [   "DBA Junior" ,"list_single_user" ],
            [   "DBA Senior" ,"list_single_user" ],
            [   "Sistema" ,"list_single_user" ],
            [   "Presidência" ,"manager" ],
            [   "Desenvolvedor" ,"manager" ],
            [   "Gerente de Contas" ,"manager" ],
            [   "Suporte" ,"manager" ],
            [   "Controle de Qualidade" ,"manager" ],
            [   "Gerente operacional" ,"manager" ],
            [   "Desenvolvedor Junior" ,"manager" ],
            [   "Desenvolvedor Senior" ,"manager" ],
            [   "DBA" ,"manager" ],
            [   "DBA Junior" ,"manager" ],
            [   "DBA Senior" ,"manager" ],
            [   "Sistema" ,"manager" ],
            [   "Presidência" ,"associate_manager" ],
            [   "Gerente operacional" ,"associate_manager" ],
            [   "Desenvolvedor Junior" ,"associate_manager" ],
            [   "Desenvolvedor Senior" ,"associate_manager" ],
            [   "DBA Junior" ,"associate_manager" ],
            [   "DBA Senior" ,"associate_manager" ],
            [   "Sistema" ,"associate_manager" ],
            [   "Presidência" ,"list_manager" ],
            [   "Desenvolvedor" ,"list_manager" ],
            [   "Gerente de Contas" ,"list_manager" ],
            [   "Controle de Qualidade" ,"list_manager" ],
            [   "Gerente operacional" ,"list_manager" ],
            [   "Desenvolvedor Junior" ,"list_manager" ],
            [   "Desenvolvedor Senior" ,"list_manager" ],
            [   "DBA" ,"list_manager" ],
            [   "DBA Junior" ,"list_manager" ],
            [   "DBA Senior" ,"list_manager" ],
            [   "Sistema" ,"list_manager" ],
            [   "Presidência" ,"list_single_manager" ],
            [   "Desenvolvedor" ,"list_single_manager" ],
            [   "Gerente de Contas" ,"list_single_manager" ],
            [   "Controle de Qualidade" ,"list_single_manager" ],
            [   "Gerente operacional" ,"list_single_manager" ],
            [   "Desenvolvedor Junior" ,"list_single_manager" ],
            [   "Desenvolvedor Senior" ,"list_single_manager" ],
            [   "DBA" ,"list_single_manager" ],
            [   "DBA Junior" ,"list_single_manager" ],
            [   "DBA Senior" ,"list_single_manager" ],
            [   "Sistema" ,"list_single_manager" ],
            [   "Presidência" ,"edit_single_user" ],
            [   "Gerente operacional" ,"edit_single_user" ],
            [   "Desenvolvedor Junior" ,"edit_single_user" ],
            [   "Desenvolvedor Senior" ,"edit_single_user" ],
            [   "DBA Junior" ,"edit_single_user" ],
            [   "DBA Senior" ,"edit_single_user" ],
            [   "Sistema" ,"edit_single_user" ],
            [   "Presidência" ,"delete_user" ],
            [   "Gerente operacional" ,"delete_user" ],
            [   "Desenvolvedor Junior" ,"delete_user" ],
            [   "Desenvolvedor Senior" ,"delete_user" ],
            [   "DBA Junior" ,"delete_user" ],
            [   "DBA Senior" ,"delete_user" ],
            [   "Sistema" ,"delete_user" ],
            [   "Presidência" ,"create_user" ],
            [   "Gerente de Contas" ,"create_user" ],
            [   "Gerente operacional" ,"create_user" ],
            [   "Presidência" ,"create_user" ],
            [   "Desenvolvedor Junior" ,"create_user" ],
            [   "Desenvolvedor Senior" ,"create_user" ],
            [   "DBA" ,"create_user" ],
            [   "Desenvolvedor" ,"create_user" ],
            [   "DBA Junior" ,"create_user" ],
            [   "DBA Senior" ,"create_user" ],
            [   "Sistema" ,"create_user" ],
            [   "Presidência" ,"passalt_single_user" ],
            [   "Gerente operacional" ,"passalt_single_user" ],
            [   "Desenvolvedor Junior" ,"passalt_single_user" ],
            [   "Desenvolvedor Senior" ,"passalt_single_user" ],
            [   "DBA Junior" ,"passalt_single_user" ],
            [   "DBA Senior" ,"passalt_single_user" ],
            [   "Sistema" ,"passalt_single_user" ],
            [   "Presidência" ,"passalt_user" ],
            [   "Gerente de Contas" ,"passalt_user" ],
            [   "Gerente operacional" ,"passalt_user" ],
            [   "Suporte" ,"passalt_user" ],
            [   "Desenvolvedor Junior" ,"passalt_user" ],
            [   "Desenvolvedor Senior" ,"passalt_user" ],
            [   "DBA Junior" ,"passalt_user" ],
            [   "DBA Senior" ,"passalt_user" ],
            [   "Sistema" ,"passalt_user" ],
            [   "Presidência" ,"edit_user" ],
            [   "Gerente operacional" ,"edit_user" ],
            [   "Desenvolvedor Junior" ,"edit_user" ],
            [   "Desenvolvedor Senior" ,"edit_user" ],
            [   "DBA Junior" ,"edit_user" ],
            [   "DBA Senior" ,"edit_user" ],
            [   "Sistema" ,"edit_user" ],
            [   "Presidência" ,"client_create" ],
            [   "Gerente de Contas" ,"client_create" ],
            [   "Gerente operacional" ,"client_create" ],
            [   "Desenvolvedor Junior" ,"client_create" ],
            [   "Desenvolvedor Senior" ,"client_create" ],
            [   "DBA Junior" ,"client_create" ],
            [   "DBA Senior" ,"client_create" ],
            [   "Sistema" ,"client_create" ],
            [   "Presidência" ,"client_list" ],
            [   "Desenvolvedor" ,"client_list" ],
            [   "Faturamento" ,"client_list" ],
            [   "Gerente de Contas" ,"client_list" ],
            [   "Financeiro" ,"client_list" ],
            [   "Cliente" ,"client_list" ],
            [   "Suporte" ,"client_list" ],
            [   "Gerente operacional" ,"client_list" ],
            [   "Desenvolvedor Junior" ,"client_list" ],
            [   "Desenvolvedor Senior" ,"client_list" ],
            [   "DBA" ,"client_list" ],
            [   "DBA Junior" ,"client_list" ],
            [   "DBA Senior" ,"client_list" ],
            [   "Sistema" ,"client_list" ],
            [   "Presidência" ,"client_list_single" ],
            [   "Desenvolvedor" ,"client_list_single" ],
            [   "Faturamento" ,"client_list_single" ],
            [   "Gerente de Contas" ,"client_list_single" ],
            [   "Financeiro" ,"client_list_single" ],
            [   "Cliente" ,"client_list_single" ],
            [   "Suporte" ,"client_list_single" ],
            [   "Gerente operacional" ,"client_list_single" ],
            [   "Desenvolvedor Junior" ,"client_list_single" ],
            [   "Desenvolvedor Senior" ,"client_list_single" ],
            [   "DBA" ,"client_list_single" ],
            [   "DBA Junior" ,"client_list_single" ],
            [   "DBA Senior" ,"client_list_single" ],
            [   "Sistema" ,"client_list_single" ],
            [   "Presidência" ,"client_edit" ],
            [   "Controle de Qualidade" ,"client_edit" ],
            [   "Gerente operacional" ,"client_edit" ],
            [   "Desenvolvedor Junior" ,"client_edit" ],
            [   "Desenvolvedor Senior" ,"client_edit" ],
            [   "DBA Junior" ,"client_edit" ],
            [   "DBA Senior" ,"client_edit" ],
            [   "Sistema" ,"client_edit" ],
            [   "Presidência" ,"client_edit" ],
            [   "Controle de Qualidade" ,"client_edit" ],
            [   "Gerente operacional" ,"client_edit" ],
            [   "Desenvolvedor Junior" ,"client_edit" ],
            [   "Desenvolvedor Senior" ,"client_edit" ],
            [   "DBA Junior" ,"client_edit" ],
            [   "DBA Senior" ,"client_edit" ],
            [   "Sistema" ,"client_edit" ],
            [   "Presidência" ,"client_edit_single" ],
            [   "Controle de Qualidade" ,"client_edit_single" ],
            [   "Gerente operacional" ,"client_edit_single" ],
            [   "Desenvolvedor Junior" ,"client_edit_single" ],
            [   "Desenvolvedor Senior" ,"client_edit_single" ],
            [   "DBA Junior" ,"client_edit_single" ],
            [   "DBA Senior" ,"client_edit_single" ],
            [   "Sistema" ,"client_edit_single" ],
            [   "Presidência" ,"client_delete" ],
            [   "Gerente operacional" ,"client_delete" ],
            [   "Desenvolvedor Junior" ,"client_delete" ],
            [   "Desenvolvedor Senior" ,"client_delete" ],
            [   "DBA Junior" ,"client_delete" ],
            [   "DBA Senior" ,"client_delete" ],
            [   "Sistema" ,"client_delete" ],
            [   "Presidência" ,"provider_create" ],
            [   "Gerente operacional" ,"provider_create" ],
            [   "Desenvolvedor Junior" ,"provider_create" ],
            [   "Desenvolvedor Senior" ,"provider_create" ],
            [   "DBA Junior" ,"provider_create" ],
            [   "DBA Senior" ,"provider_create" ],
            [   "Sistema" ,"provider_create" ],
            [   "Presidência" ,"provider_list" ],
            [   "Desenvolvedor" ,"provider_list" ],
            [   "Logística" ,"provider_list" ],
            [   "Faturamento" ,"provider_list" ],
            [   "Gerente de Contas" ,"provider_list" ],
            [   "Financeiro" ,"provider_list" ],
            [   "Suporte" ,"provider_list" ],
            [   "Controle de Qualidade" ,"provider_list" ],
            [   "Gerente operacional" ,"provider_list" ],
            [   "Desenvolvedor Junior" ,"provider_list" ],
            [   "Desenvolvedor Senior" ,"provider_list" ],
            [   "DBA" ,"provider_list" ],
            [   "DBA Junior" ,"provider_list" ],
            [   "DBA Senior" ,"provider_list" ],
            [   "Presidência" ,"provider_list_single" ],
            [   "Desenvolvedor" ,"provider_list_single" ],
            [   "Logística" ,"provider_list_single" ],
            [   "Faturamento" ,"provider_list_single" ],
            [   "Gerente de Contas" ,"provider_list_single" ],
            [   "Financeiro" ,"provider_list_single" ],
            [   "Suporte" ,"provider_list_single" ],
            [   "Controle de Qualidade" ,"provider_list_single" ],
            [   "Gerente operacional" ,"provider_list_single" ],
            [   "Desenvolvedor Junior" ,"provider_list_single" ],
            [   "Desenvolvedor Senior" ,"provider_list_single" ],
            [   "DBA" ,"provider_list_single" ],
            [   "DBA Junior" ,"provider_list_single" ],
            [   "DBA Senior" ,"provider_list_single" ],
            [   "Presidência" ,"provider_edit" ],
            [   "Gerente operacional" ,"provider_edit" ],
            [   "Desenvolvedor Junior" ,"provider_edit" ],
            [   "Desenvolvedor Senior" ,"provider_edit" ],
            [   "DBA Junior" ,"provider_edit" ],
            [   "DBA Senior" ,"provider_edit" ],
            [   "Sistema" ,"provider_edit" ],
            [   "Presidência" ,"provider_edit_single" ],
            [   "Gerente operacional" ,"provider_edit_single" ],
            [   "Desenvolvedor Junior" ,"provider_edit_single" ],
            [   "Desenvolvedor Senior" ,"provider_edit_single" ],
            [   "DBA Junior" ,"provider_edit_single" ],
            [   "DBA Senior" ,"provider_edit_single" ],
            [   "Sistema" ,"provider_edit_single" ],
            [   "Presidência" ,"provider_delete" ],
            [   "Gerente operacional" ,"provider_delete" ],
            [   "Desenvolvedor Junior" ,"provider_delete" ],
            [   "Desenvolvedor Senior" ,"provider_delete" ],
            [   "DBA Junior" ,"provider_delete" ],
            [   "DBA Senior" ,"provider_delete" ],
            [   "Sistema" ,"provider_delete" ],
            [   "Presidência" ,"prov_product_create" ],
            [   "Gerente operacional" ,"prov_product_create" ],
            [   "Desenvolvedor Junior" ,"prov_product_create" ],
            [   "Desenvolvedor Senior" ,"prov_product_create" ],
            [   "DBA Junior" ,"prov_product_create" ],
            [   "DBA Senior" ,"prov_product_create" ],
            [   "Sistema" ,"prov_product_create" ],
            [   "Presidência" ,"prov_product_list" ],
            [   "Desenvolvedor" ,"prov_product_list" ],
            [   "Logística" ,"prov_product_list" ],
            [   "Faturamento" ,"prov_product_list" ],
            [   "Gerente de Contas" ,"prov_product_list" ],
            [   "Financeiro" ,"prov_product_list" ],
            [   "Suporte" ,"prov_product_list" ],
            [   "Controle de Qualidade" ,"prov_product_list" ],
            [   "Gerente operacional" ,"prov_product_list" ],
            [   "Desenvolvedor Junior" ,"prov_product_list" ],
            [   "Desenvolvedor Senior" ,"prov_product_list" ],
            [   "DBA" ,"prov_product_list" ],
            [   "DBA Junior" ,"prov_product_list" ],
            [   "DBA Senior" ,"prov_product_list" ],
            [   "Presidência" ,"prov_product_list_single" ],
            [   "Desenvolvedor" ,"prov_product_list_single" ],
            [   "Logística" ,"prov_product_list_single" ],
            [   "Faturamento" ,"prov_product_list_single" ],
            [   "Gerente de Contas" ,"prov_product_list_single" ],
            [   "Financeiro" ,"prov_product_list_single" ],
            [   "Suporte" ,"prov_product_list_single" ],
            [   "Controle de Qualidade" ,"prov_product_list_single" ],
            [   "Gerente operacional" ,"prov_product_list_single" ],
            [   "Desenvolvedor Junior" ,"prov_product_list_single" ],
            [   "Desenvolvedor Senior" ,"prov_product_list_single" ],
            [   "DBA" ,"prov_product_list_single" ],
            [   "DBA Junior" ,"prov_product_list_single" ],
            [   "DBA Senior" ,"prov_product_list_single" ],
            [   "Presidência" ,"prov_product_edit" ],
            [   "Gerente operacional" ,"prov_product_edit" ],
            [   "Desenvolvedor Junior" ,"prov_product_edit" ],
            [   "Desenvolvedor Senior" ,"prov_product_edit" ],
            [   "DBA Junior" ,"prov_product_edit" ],
            [   "DBA Senior" ,"prov_product_edit" ],
            [   "Sistema" ,"prov_product_edit" ],
            [   "Presidência" ,"prov_product_edit_single" ],
            [   "Gerente operacional" ,"prov_product_edit_single" ],
            [   "Desenvolvedor Junior" ,"prov_product_edit_single" ],
            [   "Desenvolvedor Senior" ,"prov_product_edit_single" ],
            [   "DBA Junior" ,"prov_product_edit_single" ],
            [   "DBA Senior" ,"prov_product_edit_single" ],
            [   "Sistema" ,"prov_product_edit_single" ],
            [   "Presidência" ,"prov_product_delete" ],
            [   "Gerente operacional" ,"prov_product_delete" ],
            [   "Desenvolvedor Junior" ,"prov_product_delete" ],
            [   "Desenvolvedor Senior" ,"prov_product_delete" ],
            [   "DBA Junior" ,"prov_product_delete" ],
            [   "DBA Senior" ,"prov_product_delete" ],
            [   "Sistema" ,"prov_product_delete" ],
            [   "Presidência" ,"product_create" ],
            [   "Gerente operacional" ,"product_create" ],
            [   "Desenvolvedor Junior" ,"product_create" ],
            [   "Desenvolvedor Senior" ,"product_create" ],
            [   "DBA Junior" ,"product_create" ],
            [   "DBA Senior" ,"product_create" ],
            [   "Sistema" ,"product_create" ],
            [   "Presidência" ,"product_list" ],
            [   "Desenvolvedor" ,"product_list" ],
            [   "Logística" ,"product_list" ],
            [   "Faturamento" ,"product_list" ],
            [   "Gerente de Contas" ,"product_list" ],
            [   "Financeiro" ,"product_list" ],
            [   "Suporte" ,"product_list" ],
            [   "Controle de Qualidade" ,"product_list" ],
            [   "Gerente operacional" ,"product_list" ],
            [   "Desenvolvedor Junior" ,"product_list" ],
            [   "Desenvolvedor Senior" ,"product_list" ],
            [   "DBA" ,"product_list" ],
            [   "DBA Junior" ,"product_list" ],
            [   "DBA Senior" ,"product_list" ],
            [   "Presidência" ,"product_list_single" ],
            [   "Desenvolvedor" ,"product_list_single" ],
            [   "Logística" ,"product_list_single" ],
            [   "Faturamento" ,"product_list_single" ],
            [   "Gerente de Contas" ,"product_list_single" ],
            [   "Financeiro" ,"product_list_single" ],
            [   "Suporte" ,"product_list_single" ],
            [   "Controle de Qualidade" ,"product_list_single" ],
            [   "Gerente operacional" ,"product_list_single" ],
            [   "Desenvolvedor Junior" ,"product_list_single" ],
            [   "Desenvolvedor Senior" ,"product_list_single" ],
            [   "DBA" ,"product_list_single" ],
            [   "DBA Junior" ,"product_list_single" ],
            [   "DBA Senior" ,"product_list_single" ],
            [   "Presidência" ,"product_edit" ],
            [   "Gerente operacional" ,"product_edit" ],
            [   "Desenvolvedor Junior" ,"product_edit" ],
            [   "Desenvolvedor Senior" ,"product_edit" ],
            [   "DBA Junior" ,"product_edit" ],
            [   "DBA Senior" ,"product_edit" ],
            [   "Sistema" ,"product_edit" ],
            [   "Presidência" ,"product_edit_single" ],
            [   "Gerente operacional" ,"product_edit_single" ],
            [   "Desenvolvedor Junior" ,"product_edit_single" ],
            [   "Desenvolvedor Senior" ,"product_edit_single" ],
            [   "DBA Junior" ,"product_edit_single" ],
            [   "DBA Senior" ,"product_edit_single" ],
            [   "Sistema" ,"product_edit_single" ],
            [   "Presidência" ,"product_delete" ],
            [   "Gerente operacional" ,"product_delete" ],
            [   "Desenvolvedor Junior" ,"product_delete" ],
            [   "Desenvolvedor Senior" ,"product_delete" ],
            [   "DBA Junior" ,"product_delete" ],
            [   "DBA Senior" ,"product_delete" ],
            [   "Sistema" ,"product_delete" ],
            [   "Presidência" ,"prod_type_create" ],
            [   "Gerente operacional" ,"prod_type_create" ],
            [   "Desenvolvedor Junior" ,"prod_type_create" ],
            [   "Desenvolvedor Senior" ,"prod_type_create" ],
            [   "DBA Junior" ,"prod_type_create" ],
            [   "DBA Senior" ,"prod_type_create" ],
            [   "Sistema" ,"prod_type_create" ],
            [   "Presidência" ,"prod_type_list" ],
            [   "Desenvolvedor" ,"prod_type_list" ],
            [   "Logística" ,"prod_type_list" ],
            [   "Faturamento" ,"prod_type_list" ],
            [   "Gerente de Contas" ,"prod_type_list" ],
            [   "Financeiro" ,"prod_type_list" ],
            [   "Suporte" ,"prod_type_list" ],
            [   "Controle de Qualidade" ,"prod_type_list" ],
            [   "Gerente operacional" ,"prod_type_list" ],
            [   "Desenvolvedor Junior" ,"prod_type_list" ],
            [   "Desenvolvedor Senior" ,"prod_type_list" ],
            [   "DBA" ,"prod_type_list" ],
            [   "DBA Junior" ,"prod_type_list" ],
            [   "DBA Senior" ,"prod_type_list" ],
            [   "Presidência" ,"prod_type_list_single" ],
            [   "Desenvolvedor" ,"prod_type_list_single" ],
            [   "Logística" ,"prod_type_list_single" ],
            [   "Faturamento" ,"prod_type_list_single" ],
            [   "Gerente de Contas" ,"prod_type_list_single" ],
            [   "Financeiro" ,"prod_type_list_single" ],
            [   "Suporte" ,"prod_type_list_single" ],
            [   "Controle de Qualidade" ,"prod_type_list_single" ],
            [   "Gerente operacional" ,"prod_type_list_single" ],
            [   "Desenvolvedor Junior" ,"prod_type_list_single" ],
            [   "Desenvolvedor Senior" ,"prod_type_list_single" ],
            [   "DBA" ,"prod_type_list_single" ],
            [   "DBA Junior" ,"prod_type_list_single" ],
            [   "DBA Senior" ,"prod_type_list_single" ],
            [   "Presidência" ,"prod_type_edit" ],
            [   "Gerente operacional" ,"prod_type_edit" ],
            [   "Desenvolvedor Junior" ,"prod_type_edit" ],
            [   "Desenvolvedor Senior" ,"prod_type_edit" ],
            [   "DBA Junior" ,"prod_type_edit" ],
            [   "DBA Senior" ,"prod_type_edit" ],
            [   "Sistema" ,"prod_type_edit" ],
            [   "Presidência" ,"prod_type_edit_single" ],
            [   "Gerente operacional" ,"prod_type_edit_single" ],
            [   "Desenvolvedor Junior" ,"prod_type_edit_single" ],
            [   "Desenvolvedor Senior" ,"prod_type_edit_single" ],
            [   "DBA Junior" ,"prod_type_edit_single" ],
            [   "DBA Senior" ,"prod_type_edit_single" ],
            [   "Sistema" ,"prod_type_edit_single" ],
            [   "Presidência" ,"prod_type_delete" ],
            [   "Gerente operacional" ,"prod_type_delete" ],
            [   "Desenvolvedor Junior" ,"prod_type_delete" ],
            [   "Desenvolvedor Senior" ,"prod_type_delete" ],
            [   "DBA Junior" ,"prod_type_delete" ],
            [   "DBA Senior" ,"prod_type_delete" ],
            [   "Sistema" ,"prod_type_delete" ],
            [   "Presidência" ,"order_create" ],
            [   "Gerente operacional" ,"order_create" ],
            [   "Desenvolvedor Junior" ,"order_create" ],
            [   "Desenvolvedor Senior" ,"order_create" ],
            [   "DBA Junior" ,"order_create" ],
            [   "DBA Senior" ,"order_create" ],
            [   "Sistema" ,"order_create" ],
            [   "Presidência" ,"prod_type_delete" ],
            [   "Gerente operacional" ,"prod_type_delete" ],
            [   "Desenvolvedor Junior" ,"prod_type_delete" ],
            [   "Desenvolvedor Senior" ,"prod_type_delete" ],
            [   "DBA Junior" ,"prod_type_delete" ],
            [   "DBA Senior" ,"prod_type_delete" ],
            [   "Sistema" ,"prod_type_delete" ],
            [   "Presidência" ,"order_aprove" ],
            [   "Gerente operacional" ,"order_aprove" ],
            [   "Desenvolvedor Junior" ,"order_aprove" ],
            [   "Desenvolvedor Senior" ,"order_aprove" ],
            [   "DBA Junior" ,"order_aprove" ],
            [   "DBA Senior" ,"order_aprove" ],
            [   "Sistema" ,"order_aprove" ],
            [   "Presidência" ,"order_reprove" ],
            [   "Gerente operacional" ,"order_reprove" ],
            [   "Desenvolvedor Junior" ,"order_reprove" ],
            [   "Desenvolvedor Senior" ,"order_reprove" ],
            [   "DBA Junior" ,"order_reprove" ],
            [   "DBA Senior" ,"order_reprove" ],
            [   "Sistema" ,"order_reprove" ],
            [   "Presidência" ,"order_backoffice" ],
            [   "Gerente operacional" ,"order_backoffice" ],
            [   "Desenvolvedor Junior" ,"order_backoffice" ],
            [   "Desenvolvedor Senior" ,"order_backoffice" ],
            [   "DBA Junior" ,"order_backoffice" ],
            [   "DBA Senior" ,"order_backoffice" ],
            [   "Sistema" ,"order_backoffice" ],
            [   "Presidência" ,"order_list" ],
            [   "Desenvolvedor" ,"order_list" ],
            [   "Logística" ,"order_list" ],
            [   "Faturamento" ,"order_list" ],
            [   "Gerente de Contas" ,"order_list" ],
            [   "Financeiro" ,"order_list" ],
            [   "Suporte" ,"order_list" ],
            [   "Controle de Qualidade" ,"order_list" ],
            [   "Gerente operacional" ,"order_list" ],
            [   "Desenvolvedor Junior" ,"order_list" ],
            [   "Desenvolvedor Senior" ,"order_list" ],
            [   "DBA" ,"order_list" ],
            [   "DBA Junior" ,"order_list" ],
            [   "DBA Senior" ,"order_list" ],
            [   "Presidência" ,"order" ],
            [   "Desenvolvedor" ,"order" ],
            [   "Logística" ,"order" ],
            [   "Faturamento" ,"order" ],
            [   "Gerente de Contas" ,"order" ],
            [   "Financeiro" ,"order" ],
            [   "Suporte" ,"order" ],
            [   "Controle de Qualidade" ,"order" ],
            [   "Gerente operacional" ,"order" ],
            [   "Desenvolvedor Junior" ,"order" ],
            [   "Desenvolvedor Senior" ,"order" ],
            [   "DBA" ,"order" ],
            [   "DBA Junior" ,"order" ],
            [   "DBA Senior" ,"order" ],
            [   "Presidência" ,"order_edit" ],
            [   "Gerente operacional" ,"order_edit" ],
            [   "Desenvolvedor Junior" ,"order_edit" ],
            [   "Desenvolvedor Senior" ,"order_edit" ],
            [   "DBA Junior" ,"order_edit" ],
            [   "DBA Senior" ,"order_edit" ],
            [   "Sistema" ,"order_edit" ],
            [   "Presidência" ,"order_create" ],
            [   "Gerente operacional" ,"order_create" ],
            [   "Desenvolvedor Junior" ,"order_create" ],
            [   "Desenvolvedor Senior" ,"order_create" ],
            [   "DBA Junior" ,"order_create" ],
            [   "DBA Senior" ,"order_create" ],
            [   "Sistema" ,"order_create" ],
            [   "Presidência" ,"order_delete" ],
            [   "Gerente operacional" ,"order_delete" ],
            [   "Desenvolvedor Junior" ,"order_delete" ],
            [   "Desenvolvedor Senior" ,"order_delete" ],
            [   "DBA Junior" ,"order_delete" ],
            [   "DBA Senior" ,"order_delete" ],
            [   "Sistema" ,"order_delete" ],
            [   "Presidência" ,"order_batches_finish" ],
            [   "Gerente operacional" ,"order_batches_finish" ],
            [   "Desenvolvedor Junior" ,"order_batches_finish" ],
            [   "Desenvolvedor Senior" ,"order_batches_finish" ],
            [   "DBA Junior" ,"order_batches_finish" ],
            [   "DBA Senior" ,"order_batches_finish" ],
            [   "Sistema" ,"order_batches_finish" ],
            [   "Presidência" ,"order_finish" ],
            [   "Gerente operacional" ,"order_finish" ],
            [   "Desenvolvedor Junior" ,"order_finish" ],
            [   "Desenvolvedor Senior" ,"order_finish" ],
            [   "DBA Junior" ,"order_finish" ],
            [   "DBA Senior" ,"order_finish" ],
            [   "Sistema" ,"order_finish" ],
            [   "Presidência" ,"order_edit" ],
            [   "Gerente operacional" ,"order_edit" ],
            [   "Desenvolvedor Junior" ,"order_edit" ],
            [   "Desenvolvedor Senior" ,"order_edit" ],
            [   "DBA Junior" ,"order_edit" ],
            [   "DBA Senior" ,"order_edit" ],
            [   "Sistema" ,"order_edit" ],
            [   "Presidência" ,"order_delete" ],
            [   "Gerente operacional" ,"order_delete" ],
            [   "Desenvolvedor Junior" ,"order_delete" ],
            [   "Desenvolvedor Senior" ,"order_delete" ],
            [   "DBA Junior" ,"order_delete" ],
            [   "DBA Senior" ,"order_delete" ],
            [   "Sistema" ,"order_delete" ],
            [   "Presidência" ,"order_item" ],
            [   "Desenvolvedor" ,"order_item" ],
            [   "Logística" ,"order_item" ],
            [   "Faturamento" ,"order_item" ],
            [   "Gerente de Contas" ,"order_item" ],
            [   "Financeiro" ,"order_item" ],
            [   "Suporte" ,"order_item" ],
            [   "Controle de Qualidade" ,"order_item" ],
            [   "Gerente operacional" ,"order_item" ],
            [   "Desenvolvedor Junior" ,"order_item" ],
            [   "Desenvolvedor Senior" ,"order_item" ],
            [   "DBA" ,"order_item" ],
            [   "DBA Junior" ,"order_item" ],
            [   "DBA Senior" ,"order_item" ],
            [   "Presidência" ,"order_item_create" ],
            [   "Gerente operacional" ,"order_item_create" ],
            [   "Desenvolvedor Junior" ,"order_item_create" ],
            [   "Desenvolvedor Senior" ,"order_item_create" ],
            [   "DBA Junior" ,"order_item_create" ],
            [   "DBA Senior" ,"order_item_create" ],
            [   "Sistema" ,"order_item_create" ],
            [   "Presidência" ,"order_item_list" ],
            [   "Desenvolvedor" ,"order_item_list" ],
            [   "Logística" ,"order_item_list" ],
            [   "Faturamento" ,"order_item_list" ],
            [   "Gerente de Contas" ,"order_item_list" ],
            [   "Financeiro" ,"order_item_list" ],
            [   "Suporte" ,"order_item_list" ],
            [   "Controle de Qualidade" ,"order_item_list" ],
            [   "Gerente operacional" ,"order_item_list" ],
            [   "Desenvolvedor Junior" ,"order_item_list" ],
            [   "Desenvolvedor Senior" ,"order_item_list" ],
            [   "DBA" ,"order_item_list" ],
            [   "DBA Junior" ,"order_item_list" ],
            [   "DBA Senior" ,"order_item_list" ],
            [   "Presidência" ,"order_item_edit" ],
            [   "Gerente operacional" ,"order_item_edit" ],
            [   "Desenvolvedor Junior" ,"order_item_edit" ],
            [   "Desenvolvedor Senior" ,"order_item_edit" ],
            [   "DBA Junior" ,"order_item_edit" ],
            [   "DBA Senior" ,"order_item_edit" ],
            [   "Sistema" ,"order_item_edit" ],
            [   "Presidência" ,"order_item_delte" ],
            [   "Gerente operacional" ,"order_item_delte" ],
            [   "Desenvolvedor Junior" ,"order_item_delte" ],
            [   "Desenvolvedor Senior" ,"order_item_delte" ],
            [   "DBA Junior" ,"order_item_delte" ],
            [   "DBA Senior" ,"order_item_delte" ],
            [   "Sistema" ,"order_item_delte" ],
            [   "Presidência" ,"order_batch" ],
            [   "Desenvolvedor" ,"order_batch" ],
            [   "Logística" ,"order_batch" ],
            [   "Faturamento" ,"order_batch" ],
            [   "Gerente de Contas" ,"order_batch" ],
            [   "Financeiro" ,"order_batch" ],
            [   "Suporte" ,"order_batch" ],
            [   "Controle de Qualidade" ,"order_batch" ],
            [   "Gerente operacional" ,"order_batch" ],
            [   "Desenvolvedor Junior" ,"order_batch" ],
            [   "Desenvolvedor Senior" ,"order_batch" ],
            [   "DBA" ,"order_batch" ],
            [   "DBA Junior" ,"order_batch" ],
            [   "DBA Senior" ,"order_batch" ],
            [   "Presidência" ,"order_batch_create" ],
            [   "Gerente operacional" ,"order_batch_create" ],
            [   "Desenvolvedor Junior" ,"order_batch_create" ],
            [   "Desenvolvedor Senior" ,"order_batch_create" ],
            [   "DBA Junior" ,"order_batch_create" ],
            [   "DBA Senior" ,"order_batch_create" ],
            [   "Sistema" ,"order_batch_create" ],
            [   "Presidência" ,"order_batch_list" ],
            [   "Desenvolvedor" ,"order_batch_list" ],
            [   "Logística" ,"order_batch_list" ],
            [   "Faturamento" ,"order_batch_list" ],
            [   "Gerente de Contas" ,"order_batch_list" ],
            [   "Financeiro" ,"order_batch_list" ],
            [   "Suporte" ,"order_batch_list" ],
            [   "Controle de Qualidade" ,"order_batch_list" ],
            [   "Gerente operacional" ,"order_batch_list" ],
            [   "Desenvolvedor Junior" ,"order_batch_list" ],
            [   "Desenvolvedor Senior" ,"order_batch_list" ],
            [   "DBA" ,"order_batch_list" ],
            [   "DBA Junior" ,"order_batch_list" ],
            [   "DBA Senior" ,"order_batch_list" ],
            [   "Presidência" ,"order_batch_edit" ],
            [   "Gerente operacional" ,"order_batch_edit" ],
            [   "Desenvolvedor Junior" ,"order_batch_edit" ],
            [   "Desenvolvedor Senior" ,"order_batch_edit" ],
            [   "DBA Junior" ,"order_batch_edit" ],
            [   "DBA Senior" ,"order_batch_edit" ],
            [   "Sistema" ,"order_batch_edit" ],
            [   "Presidência" ,"order_batch_delete" ],
            [   "Gerente operacional" ,"order_batch_delete" ],
            [   "Desenvolvedor Junior" ,"order_batch_delete" ],
            [   "Desenvolvedor Senior" ,"order_batch_delete" ],
            [   "DBA Junior" ,"order_batch_delete" ],
            [   "DBA Senior" ,"order_batch_delete" ],
            [   "Sistema" ,"order_batch_delete" ],
            [   "Presidência" ,"order_batch_link" ],
            [   "Gerente operacional" ,"order_batch_link" ],
            [   "Desenvolvedor Junior" ,"order_batch_link" ],
            [   "Desenvolvedor Senior" ,"order_batch_link" ],
            [   "DBA Junior" ,"order_batch_link" ],
            [   "DBA Senior" ,"order_batch_link" ],
            [   "Sistema" ,"order_batch_link" ],
            [   "Presidência" ,"order_batch_finish" ],
            [   "Gerente operacional" ,"order_batch_finish" ],
            [   "Desenvolvedor Junior" ,"order_batch_finish" ],
            [   "Desenvolvedor Senior" ,"order_batch_finish" ],
            [   "DBA Junior" ,"order_batch_finish" ],
            [   "DBA Senior" ,"order_batch_finish" ],
            [   "Sistema" ,"order_batch_finish" ],
            [   "Presidência" ,"stock_view" ],
            [   "Desenvolvedor" ,"stock_view" ],
            [   "Logística" ,"stock_view" ],
            [   "Desenvolvedor Junior" ,"stock_view" ],
            [   "Desenvolvedor Senior" ,"stock_view" ],
            [   "Sistema" ,"stock_view" ],
            [   "Presidência" ,"stock_list" ],
            [   "Desenvolvedor" ,"stock_list" ],
            [   "Gerente de Contas" ,"stock_list" ],
            [   "Suporte" ,"stock_list" ],
            [   "Controle de Qualidade" ,"stock_list" ],
            [   "Gerente operacional" ,"stock_list" ],
            [   "Desenvolvedor Junior" ,"stock_list" ],
            [   "Desenvolvedor Senior" ,"stock_list" ],
            [   "DBA" ,"stock_list" ],
            [   "DBA Junior" ,"stock_list" ],
            [   "DBA Senior" ,"stock_list" ],
            [   "Sistema" ,"stock_list" ],
            [   "Presidência" ,"stock_orders_" ],
            [   "Desenvolvedor" ,"stock_orders_" ],
            [   "Gerente de Contas" ,"stock_orders_" ],
            [   "Suporte" ,"stock_orders_" ],
            [   "Controle de Qualidade" ,"stock_orders_" ],
            [   "Gerente operacional" ,"stock_orders_" ],
            [   "Desenvolvedor Junior" ,"stock_orders_" ],
            [   "Desenvolvedor Senior" ,"stock_orders_" ],
            [   "DBA" ,"stock_orders_" ],
            [   "DBA Junior" ,"stock_orders_" ],
            [   "DBA Senior" ,"stock_orders_" ],
            [   "Sistema" ,"stock_orders_" ],
            [   "Presidência" ,"invoice_view" ],
            [   "Desenvolvedor" ,"invoice_view" ],
            [   "Faturamento" ,"invoice_view" ],
            [   "Suporte" ,"invoice_view" ],
            [   "Gerente operacional" ,"invoice_view" ],
            [   "Desenvolvedor Junior" ,"invoice_view" ],
            [   "Desenvolvedor Senior" ,"invoice_view" ],
            [   "Sistema" ,"invoice_view" ],
            [   "Gerente de contratos" ,"invoice_view" ],
            [   "Presidência" ,"invoice_export_detailed" ],
            [   "Desenvolvedor" ,"invoice_export_detailed" ],
            [   "Faturamento" ,"invoice_export_detailed" ],
            [   "Suporte" ,"invoice_export_detailed" ],
            [   "Gerente operacional" ,"invoice_export_detailed" ],
            [   "Desenvolvedor Junior" ,"invoice_export_detailed" ],
            [   "Desenvolvedor Senior" ,"invoice_export_detailed" ],
            [   "Sistema" ,"invoice_export_detailed" ],
            [   "Gerente de contratos" ,"invoice_export_detailed" ],
            [   "Presidência" ,"invoice_export" ],
            [   "Desenvolvedor" ,"invoice_export" ],
            [   "Faturamento" ,"invoice_export" ],
            [   "Suporte" ,"invoice_export" ],
            [   "Gerente operacional" ,"invoice_export" ],
            [   "Desenvolvedor Junior" ,"invoice_export" ],
            [   "Desenvolvedor Senior" ,"invoice_export" ],
            [   "Sistema" ,"invoice_export" ],
            [   "Gerente de contratos" ,"invoice_export" ],
            [   "Presidência" ,"invoice_create" ],
            [   "Desenvolvedor" ,"invoice_create" ],
            [   "Gerente de Contas" ,"invoice_create" ],
            [   "Suporte" ,"invoice_create" ],
            [   "Controle de Qualidade" ,"invoice_create" ],
            [   "Gerente operacional" ,"invoice_create" ],
            [   "Desenvolvedor Junior" ,"invoice_create" ],
            [   "Desenvolvedor Senior" ,"invoice_create" ],
            [   "DBA" ,"invoice_create" ],
            [   "DBA Junior" ,"invoice_create" ],
            [   "DBA Senior" ,"invoice_create" ],
            [   "Sistema" ,"invoice_create" ],
            [   "Presidência" ,"invoice_edit" ],
            [   "Desenvolvedor" ,"invoice_edit" ],
            [   "Gerente de Contas" ,"invoice_edit" ],
            [   "Suporte" ,"invoice_edit" ],
            [   "Controle de Qualidade" ,"invoice_edit" ],
            [   "Gerente operacional" ,"invoice_edit" ],
            [   "Desenvolvedor Junior" ,"invoice_edit" ],
            [   "Desenvolvedor Senior" ,"invoice_edit" ],
            [   "DBA" ,"invoice_edit" ],
            [   "DBA Junior" ,"invoice_edit" ],
            [   "DBA Senior" ,"invoice_edit" ],
            [   "Sistema" ,"invoice_edit" ],
            [   "Presidência" ,"inventory_cancel" ],
            [   "Desenvolvedor" ,"inventory_cancel" ],
            [   "Suporte" ,"inventory_cancel" ],
            [   "Desenvolvedor Junior" ,"inventory_cancel" ],
            [   "Desenvolvedor Senior" ,"inventory_cancel" ],
            [   "Sistema" ,"inventory_cancel" ],
            [   "Presidência" ,"inventory_edit" ],
            [   "Desenvolvedor" ,"inventory_edit" ],
            [   "Gerente de Contas" ,"inventory_edit" ],
            [   "Suporte" ,"inventory_edit" ],
            [   "Controle de Qualidade" ,"inventory_edit" ],
            [   "Gerente operacional" ,"inventory_edit" ],
            [   "Desenvolvedor Junior" ,"inventory_edit" ],
            [   "Desenvolvedor Senior" ,"inventory_edit" ],
            [   "DBA" ,"inventory_edit" ],
            [   "DBA Junior" ,"inventory_edit" ],
            [   "DBA Senior" ,"inventory_edit" ],
            [   "Sistema" ,"inventory_edit" ],
            [   "Presidência" ,"inventory_create" ],
            [   "Desenvolvedor" ,"inventory_create" ],
            [   "Gerente de Contas" ,"inventory_create" ],
            [   "Suporte" ,"inventory_create" ],
            [   "Controle de Qualidade" ,"inventory_create" ],
            [   "Gerente operacional" ,"inventory_create" ],
            [   "Desenvolvedor Junior" ,"inventory_create" ],
            [   "Desenvolvedor Senior" ,"inventory_create" ],
            [   "DBA" ,"inventory_create" ],
            [   "DBA Junior" ,"inventory_create" ],
            [   "DBA Senior" ,"inventory_create" ],
            [   "Sistema" ,"inventory_create" ],
            [   "Presidência" ,"inventory_view" ],
            [   "Desenvolvedor" ,"inventory_view" ],
            [   "Gerente de Contas" ,"inventory_view" ],
            [   "Suporte" ,"inventory_view" ],
            [   "Controle de Qualidade" ,"inventory_view" ],
            [   "Gerente operacional" ,"inventory_view" ],
            [   "Desenvolvedor Junior" ,"inventory_view" ],
            [   "Desenvolvedor Senior" ,"inventory_view" ],
            [   "DBA" ,"inventory_view" ],
            [   "DBA Junior" ,"inventory_view" ],
            [   "DBA Senior" ,"inventory_view" ],
            [   "Sistema" ,"inventory_view" ],
            [   "Presidência" ,"sim_create" ],
            [   "Desenvolvedor" ,"sim_create" ],
            [   "Gerente de Contas" ,"sim_create" ],
            [   "Suporte" ,"sim_create" ],
            [   "Controle de Qualidade" ,"sim_create" ],
            [   "Gerente operacional" ,"sim_create" ],
            [   "Desenvolvedor Junior" ,"sim_create" ],
            [   "Desenvolvedor Senior" ,"sim_create" ],
            [   "DBA" ,"sim_create" ],
            [   "DBA Junior" ,"sim_create" ],
            [   "DBA Senior" ,"sim_create" ],
            [   "Sistema" ,"sim_create" ],
            [   "Presidência" ,"sim_list" ],
            [   "Desenvolvedor" ,"sim_list" ],
            [   "Desenvolvedor Junior" ,"sim_list" ],
            [   "Desenvolvedor Senior" ,"sim_list" ],
            [   "Sistema" ,"sim_list" ],
            [   "Presidência" ,"sim_edit" ],
            [   "Desenvolvedor" ,"sim_edit" ],
            [   "Gerente de Contas" ,"sim_edit" ],
            [   "Suporte" ,"sim_edit" ],
            [   "Controle de Qualidade" ,"sim_edit" ],
            [   "Gerente operacional" ,"sim_edit" ],
            [   "Desenvolvedor Junior" ,"sim_edit" ],
            [   "Desenvolvedor Senior" ,"sim_edit" ],
            [   "DBA" ,"sim_edit" ],
            [   "DBA Junior" ,"sim_edit" ],
            [   "DBA Senior" ,"sim_edit" ],
            [   "Sistema" ,"sim_edit" ],
            [   "Presidência" ,"sim_delete" ],
            [   "Desenvolvedor" ,"sim_delete" ],
            [   "Gerente de Contas" ,"sim_delete" ],
            [   "Suporte" ,"sim_delete" ],
            [   "Controle de Qualidade" ,"sim_delete" ],
            [   "Gerente operacional" ,"sim_delete" ],
            [   "Desenvolvedor Junior" ,"sim_delete" ],
            [   "Desenvolvedor Senior" ,"sim_delete" ],
            [   "DBA" ,"sim_delete" ],
            [   "DBA Junior" ,"sim_delete" ],
            [   "DBA Senior" ,"sim_delete" ],
            [   "Sistema" ,"sim_delete" ],
            [   "Presidência" ,"sim_activate" ],
            [   "Desenvolvedor" ,"sim_activate" ],
            [   "Suporte" ,"sim_activate" ],
            [   "Desenvolvedor Junior" ,"sim_activate" ],
            [   "Desenvolvedor Senior" ,"sim_activate" ],
            [   "Sistema" ,"sim_activate" ],
            [   "Presidência" ,"sim_reset" ],
            [   "Desenvolvedor" ,"sim_reset" ],
            [   "Suporte" ,"sim_reset" ],
            [   "Desenvolvedor Junior" ,"sim_reset" ],
            [   "Desenvolvedor Senior" ,"sim_reset" ],
            [   "Sistema" ,"sim_reset" ],
            [   "Presidência" ,"sim_associate" ],
            [   "Desenvolvedor" ,"sim_associate" ],
            [   "Suporte" ,"sim_associate" ],
            [   "Desenvolvedor Junior" ,"sim_associate" ],
            [   "Desenvolvedor Senior" ,"sim_associate" ],
            [   "Sistema" ,"sim_associate" ],
            [   "Presidência" ,"sim_dissociate" ],
            [   "Desenvolvedor" ,"sim_dissociate" ],
            [   "Suporte" ,"sim_dissociate" ],
            [   "Desenvolvedor Junior" ,"sim_dissociate" ],
            [   "Desenvolvedor Senior" ,"sim_dissociate" ],
            [   "Sistema" ,"sim_dissociate" ],
            [   "Presidência" ,"sim_dispatch" ],
            [   "Desenvolvedor" ,"sim_dispatch" ],
            [   "Suporte" ,"sim_dispatch" ],
            [   "Desenvolvedor Junior" ,"sim_dispatch" ],
            [   "Desenvolvedor Senior" ,"sim_dispatch" ],
            [   "Sistema" ,"sim_dispatch" ],
            [   "Presidência" ,"manager" ],
            [   "Presidência" ,"re_stock" ],
            [   "Gerente operacional" ,"re_stock" ],
            [   "Gerente de contratos" ,"order_list" ],
            [   "Gerente de contratos" ,"user" ],
            [   "Gerente de Contas" ,"order_create" ],
            [   "Gerente de Contas" ,"update_contacts" ],
            [   "Suporte" ,"update_contacts" ],
            [   "Controle de Qualidade" ,"update_contacts" ],
            [   "Gerente operacional" ,"update_contacts" ],
            [   "Gerente comercial" ,"update_contacts" ],
            [   "Presidência" ,"update_contacts" ],
            [   "Desenvolvedor" ,"update_contacts" ],
            [   "Sistema" ,"update_contacts" ],
            [   "Presidência" ,"update_addresses" ],
            [   "Gerente operacional" ,"stock_view" ],
            [   "Gerente de contratos" ,"order_aprove" ],
            [   "Gerente de contratos" ,"order_reprove" ],
            [   "Gerente de canais" ,"order_list" ],
            [   "Gerente de canais" ,"user" ],
            [   "Gerente de canais" ,"client_list" ],
            [   "Gerente de canais" ,"sim_list" ],
            [   "Gerente de canais" ,"invoice_view" ],
            [   "Gerente de canais" ,"list_user" ],
            [   "Gerente de canais" ,"order_create" ],
            [   "Gerente de canais" ,"product_list" ],
            [   "Logística" ,"order_backoffice" ],
            [   "Presidência" ,"create_stock" ],
            [   "Suporte" ,"sim_list" ],
            [   "Gerente de Contas" ,"sim_list" ],
            [   "Gerente operacional" ,"sim_list" ],
            [   "Gerente comercial" ,"sim_list" ],
            [   "Suporte" ,"list_manager" ],
            [   "Presidência" ,"client_create" ],
            [   "Desenvolvedor" ,"client_create" ],
            [   "Gerente de Contas" ,"client_create" ],
            [   "Gerente comercial" ,"client_create" ],
            [   "Gerente de canais" ,"client_create" ],
            [   "Gerente de canais" ,"list_manager" ],
            [   "Gerente de canais" ,"manager" ],
            [   "Gerente de Contas" ,"edit_user" ],
            [   "Gerente de Contas" ,"passalt_single_user" ]
        ];

        Schema::disableForeignKeyConstraints();
        DB::table('permission_map')->truncate();
        foreach ($permisson_map as $map) {
            
            $item = [];

            $permissionName = $map[0];
            $permission = Permission::where('name', $permissionName)->first();
            if(is_null($permission))
                throw new \Exception("unable to find permission: $permissionName", 1);

            $item['permission_id'] = $permission->id;


            $permissionItemCode = $map[1];
            $permissionItem = PermissionItem::where('code', $permissionItemCode)->first();
            if(is_null($permissionItem))
                throw new \Exception("unable to find Permission Item: $permissionItemCode", 1);

            $item['permission_item_id'] = $permissionItem->id;


            $this->command->info('Inserted map from' .  $permissionName . ' [' . count($map) . ']..');
            PermissionMap::create($item);
        }
        Schema::enableForeignKeyConstraints();
    }
}
